# location names to be referenced in Locations.py

# progression/important item locations
fork_pickup = "CR: Fork - vanilla fork location" # Kril's main weapon
heartkelp_inital = "Heartkelp Pods Pickup" # the initial heartkelp pods item that the player picks up right at the beginning of the game
fishing_line = "FSB: Fishing Line - vanilla fishing line location" # grapple ability found in fort slacktide
pristine_pearl = "MSC: Pristine Pearl - dropped by area boss" # reward for defeating platoon pathfinder
map_piece_vale = "FV: Map Piece - mailbox, after area boss" # the map piece found in the mailbox in flotsam vale
map_piece_heikea_arena = "EGM: Map Piece - dropped by area boss" # the map piece in heikea's boss arena after defeating them
map_piece_pagurus_defeat = "SB: Map Piece - dropped by area boss" # the map piece obtained after defeating pagurus
home_shell = "Home Shell" # kril's shell, completion location

# currency item locations
breadclaw_caveofrespite_ledge = "CR: Breadclaw - ledge after intro" # the first breadclaw the player has access to, in the cave of respite
chipclaw_caveofrespite_forkroomfishing = "CR: Chipclaw - spearfishing, near fork pickup"
mussel_caveofrespite_crabfightfishing = "CR: Mussel - spearfishing, crab fight tutorial"
clothesclaw_caveofrespite_entrancefishing = "CR: Clothesclaw - spearfishing, near cave entrance"
sanddollar_caveofrespite_pathfishing = "CR: Sand Dollar - spearfishing, path before cave"

breadclaw_shallows_southsandal = "CS: Breadclaw - red sandal, south"
breadclaw_shallows_westwall = "CS: Breadclaw - along west wall"
breadclaw_shallows_bridge = "CS: Breadclaw - red sandal bridge"
breadclaw_shallows_eastwall = "CS: Breadclaw - along east wall"
breadclaw_shallows_eastsandal = "CS: Breadclaw - red sandal, east"
breadclaw_shallows_cigarette = "CS: Breadclaw - cigarette butt mound" # breadclaw on the mound of cigarette butts near nephro's arena
breadclaw_shallows_fortwall = "CS: Breadclaw - along Fort Slacktide wall"
breadclaw_shallows_wallpiece = "CS: Breadclaw - broken fort wall, east"
breadclaw_shallows_sandcastle = "CS: Breadclaw - sandcastle, southeast"
breadclaw_shallows_eastledge = "CS: Breadclaw - grapple to ledge, east"
hairclaw_shallows_turret = "CS: Hairclaw - grapple to castle turret"
chipclaw_shallows_sandcastle = "CS: Chipclaw - sandcastle, southwest"
clothesclaw_shallows_shellsplitter = "CS: Clothesclaw - dropped by area miniboss"
clothesclaw_shallows_southwestfort = "CS: Clothesclaw - small tower outside fort, southwest"
breadclaw_shallows_sunkentower = "CS: Breadclaw - sunken tower, near red sandal bridge"
breadclaw_shallows_slacktidesouthfish = "CS: Breadclaw - spearfishing, slacktide entrance, south"

breadclaw_slacktide_crates = "FSB: Breadclaw - sand crates near duchess waiting line" # the breadclaw near the line of people waiting to meet the duchess
breadclaw_slacktide_training = "FSB: Breadclaw - training area wall, south"

breadclaw_snailcave_entrance = "MSC: Breadclaw - ledge near entrance"
breadclaw_snailcave_shortcut = "MSC: Breadclaw - ledge near shortcut"
breadclaw_snailcave_jelly = "MSC: Breadclaw - ledge past first moon jelly"

breadclaw_slacktide_crabtrio = "FSA: Breadclaw - near crab trio" # breadclaw found in slacktide post-corruption sitting in a corner near a trio of crabs
chipclaw_slacktide_brokenwall = "FSA: Chipclaw - behind broken wall" # chipclaw found in the room after the enemy breaks out of the wall on the way to fight the duchess
breadclaw_slacktide_roofhiddenfish = "FSA: Breadclaw - spearfishing, path to roof"

chipclaw_reefsedge_brokenbridge = "RE: Chipclaw - broken bridge"
breadclaw_reefsedge_thimblecrab = "RE: Breadclaw - near thimble crab"
hairclaw_reefsedge_sign = "RE: Hairclaw - on ledge near I95 sign"

breadclaw_newcarcinia_entrance = "NC: Breadclaw - building rooftops, near entrance"
breadclaw_newcarcinia_hammerhead = "NC: Breadclaw - corner near Hammerhead"
breadclaw_newcarcinia_bottomalley = "NC: Breadclaw - alleyway near Bottom Feeders"
breadclaw_newcarcinia_prawnalley = "NC: Breadclaw - alleyway across from Prawn Shop"
chipclaw_newcarcinia_leg = "NC: Chipclaw - building near mannequin leg"
breadclaw_newcarcinia_tallbuilding = "NC: Breadclaw - building across from Prawn Shop"
breadclaw_newcarcinia_shortbuilding = "NC: Breadclaw - building across from mannequin leg"
chipclaw_newcarcinia_prawnshop = "NC: Chipclaw - top of Prawn Shop"

breadclaw_sandsbetween_centralvista = "SB: Breadclaw - central vista base"
hairclaw_sandsbetween_southernreef = "SB: Hairclaw - above bobbit worm, south"
chipclaw_sandsbetween_grove = "SB: Chipclaw - near Expired Grove entrance"
breadclaw_sandsbetween_chains = "SB: Breadclaw - near chains, west"
clothesclaw_sandsbetween_bobbit = "SB: Clothesclaw - second terrace, bobbit den"
hairclaw_sandsbetween_bobbit = "SB: Hairclaw - third terrace, bobbit den"
clothesclaw_sandsbetween_northwest = "SB: Clothesclaw - rock near central vista, northwest"
clothesclaw_sandsbetween_grove = "SB: Clothesclaw - cans near Expired Grove entrance"
breadclaw_sandsbetween_propanecliff = "SB: Breadclaw - cliff near propane tank"
hairclaw_sandsbetween_northchains = "SB: Hairclaw - near chains, north"
clothesclaw_sandsbetween_coolerpitfall = "SB: Clothesclaw - pitfall near cooler lid"
hairclaw_sandsbetween_southgrovepit = "SB: Hairclaw - pitfall near Expired Grove entrance, south"
paperclaw_sandsbetween_southeelshortcut = "SB: Paperclaw - eelectrocute path near shortcut, south"
hairclaw_sandsbetween_southeel = "SB: Hairclaw - eelectrocute path, south"
paperclaw_sandsbetween_trashanchor = "SB: Paperclaw - trashbag near anchor"
hairclaw_sandsbetween_anchorfish = "SB: Hairclaw - spearfishing, near anchor"
chipclaw_sandsbetween_northeastchainfish = "SB: Chipclaw - spearfishing, chains, northeast"
clothesclaw_sandsbetween_propanefish = "SB: Clothesclaw - spearfishing, near propane tank"
clothesclaw_sandsbetween_anchorcentralfish = "SB: Clothesclaw - spearfishing, between central vista and anchor"
breadclaw_sandsbetween_nailfish = "SB: Breadclaw - spearfishing, near nail"
breadclaw_sandsbetween_palletfish = "SB: Breadclaw - spearfishing, wooden pallet"
hairclaw_sandsbetween_southeelfish = "SB: Hairclaw - spearfishing, eelectrocute path, south"
chipclaw_sandsbetween_anchoreelhiddenfish = "SB: Chipclaw - spearfishing, cliff near anchor"

stapleclaw_postpag_litter = "SB: Stapleclaw - post pagurus, litterbox"
hairclaw_postpag_chains = "SB: Hairclaw - post pagurus, middle of chains"
clothesclaw_postpag_chains = "SB: Clothesclaw - post pagurus, middle of chains"
hairclaw_postpag_nridge = "SB: Hairclaw - post pagurus, ridge overlook, north"
hairclaw_postpag_ecentral = "SB: Hairclaw - post pagurus, central vista, east"
chipclaw_postpag_nwpropane = "SB: Chipclaw - post pagurus, life preserver near propane"
paperclaw_postpag_schain = "SB: Paperclaw - post pagurus, chains, south"

clothesclaw_ridge_neridge = "SR: Clothesclaw - to the northeast"
paperclaw_ridge_nearoverlook = "SR: Paperclaw - ridge overlook, hidden crab"
clothesclaw_ridge_broom = "SR: Clothesclaw - near broom"
breadclaw_ridge_south = "SR: Breadclaw - southern path"
clothesclaw_ridge_overlookfish = "SR: Clothesclaw - spearfishing, ridge overlook"
chipclaw_ridge_southfish = "SR: Chipclaw - spearfishing, ridge overlook, south"

stapleclaw_trashbin_eelfish = "SR: Stapleclaw - spearfishing, eelectrocute grapple path"

breadclaw_grovemain_takeout = "EGM: Breadclaw - takeout container, east"
breadclaw_grovemain_tiretop = "EGM: Breadclaw - near tire archway"
chipclaw_grovemain_plastic = "EGM: Chipclaw - plastic silverware"
clothesclaw_grovemain_choccymilk = "EGM: Clothesclaw - chocolate milk carton"
breadclaw_grovemain_insidetire = "EGM: Breadclaw - inside tire archway"
chipclaw_grovemain_sniper = "EGM: Chipclaw - sniper ledge, east"
hairclaw_grovemain_milkurchins = "EGM: Hairclaw - milk carton urchins"
breadclaw_grovemain_smallhall = "EGM: Breadclaw - small connecting hallway"
chipclaw_grovemain_apples = "EGM: Chipclaw - rotten apple cores"
chipclaw_grovemain_sodacans = "EGM: Chipclaw - shopping cart, soda cans"
hairclaw_grovemain_moonshine = "EGM: Hairclaw - shopping cart, liquor bottle"
chipclaw_grovemain_circlerock = "EGM: Chipclaw - circular rock past shopping cart"
clothesclaw_grovemain_alcove = "EGM: Clothesclaw - gunk river alcove, near waterfall"
hairclaw_grovemain_sniper = "EGM: Hairclaw - elevated sniper platform"
breadclaw_grovemain_amongus = "EGM: Breadclaw - among us fries"
breadclaw_grovemain_oildrum = "EGM: Breadclaw - small platform near oil drum"
breadclaw_grovemain_oilgrapple = "EGM: Breadclaw - grapple near top of oil drum"
clothesclaw_grovemain_mantisfish = "EGM: Clothesclaw - spearfishing, near mantis block"
hairclaw_grovemain_fishing = "EGM: Hairclaw - spearfishing, near milk carton"
clothesclaw_grovemain_riverfish = "EGM: Clothesclaw - spearfishing, river near miniboss waterfall"

breadclaw_grovevillage_oildrum = "EGV: Breadclaw - past oil drum"
breadclaw_grovevillage_bottle1 = "EGV: Breadclaw - bottle near mantis block"
breadclaw_grovevillage_bottle2 = "EGV: Breadclaw - bottle near mantis block 2"
chipclaw_grovevillage_netorbs = "EGV: Chipclaw - near net orbs, after boss"
hairclaw_grovevillage_river = "EGV: Hairclaw spearfishing, river before oil drum"
chipclaw_grovevillage_NWcarton = "EGV: Chipclaw - milk carton, northwest"
chipclaw_grovevillage_SEcarton = "EGV: Chipclaw - milk carton, southeast"
chipclaw_grovevillage_NEcarton = "EGV: Chipclaw - milk carton, northeast"
breadclaw_grovevillage_shortcut = "EGV: Breadclaw - near cave shortcut"
chipclaw_grovevillage_cave = "EGV: Chipclaw - near end of cave"
hairclaw_grovevillage_entrance = "EGV: Hairclaw - near village entrance"
breadclaw_grovevillage_Scarton = "EGV: Breadclaw - milk carton, south"
breadclaw_grovevillage_entrance = "EGV: Breadclaw - bottles near village entrance"
hairclaw_grovevillage_NEcarton = "EGV: Hairclaw - high milk carton, northeast"
clothesclaw_grovevillage_upsidedown = "EGV: Clotheclaw - upside down village"
clothesclaw_grovevillage_dock = "EGV: Clothesclaw - spearfishing, dock"
hairclaw_grovevillage_dock = "EGV: Hairclaw - spearfishing, dock"
clothesclaw_grovevillage_hidden = "EGV: Clothesclaw - spearfishing, path to boss"
carclaw_grovevillage_topoda = "EGV: Carclaw - boss arena, after boss fight"

chipclaw_flotsamvale_sheetmetal = "FV: Chipclaw - sheet metal, near entrance"
chipclaw_flotsamvale_beach = "FV: Chipclaw - beach near entrance, north"
breadclaw_flotsamvale_northgunk = "FV: Breadclaw - in gunk near entrance, north"
chipclaw_flotsamvale_butaneisland = "FV: Chipclaw - butane tank island"
clothesclaw_flotsamvale_butaneisland = "FV: Clothesclaw - butane tank island"
clothesclaw_flotsamvale_alcove = "FV: Clothesclaw - small alcove, northeast"
chipclaw_flotsamvale_cavepath = "FV: Chipclaw - cave path toward upper Flotsam Vale"
clothesclaw_flotsamvale_cavepath = "FV: Clothesclaw - cave path toward upper Flotsam Vale"
paperclaw_flotsamvale_uppersnail = "FV: Paperclaw - upper Flotsam Vale, moon snail shell"
breadclaw_flotsamvale_woodplatform = "FV: Breadclaw - wooden platform, above area miniboss"
clothesclaw_flotsamvale_woodplatform = "FV: Clothesclaw - wooden platform, above area miniboss"
hairclaw_flotsamvale_woodplatform = "FV: Hairclaw - wooden platform, above area miniboss"
clothesclaw_flotsamvale_trashpile = "FV: Clothesclaw - trash pile, near area miniboss"
paperclaw_flotsamvale_southbutane = "FV: Paperclaw - butane tank, south of miniboss"
chipclaw_flotsamvale_westbutane = "FV: Chipclaw - butane tank, west of miniboss"
breadclaw_flotsamvale_crane = "FV: Breadclaw - near crane switch"
hairclaw_flotsamvale_mailboxbutane = "FV: Hairclaw - butane tank, southwest of mailbox"
paperclaw_flotsamvale_mailboxplatform = "FV: Paperclaw - elevated platform, southwest of mailbox"
chipclaw_flotsamvale_APunder1 = "FV: Chipclaw - air pocket cave, underwater"
hairclaw_flotsamvale_APabove1 = "FV: Hairclaw - air pocket cave, above water"
hairclaw_flotsamvale_APunder1 = "FV: Hairclaw - air pocket cave, underwater"
hairclaw_flotsamvale_APunder2 = "FV: Hairclaw - air pocket cave, underwater 2"
chipclaw_flotsamvale_APunder2 = "FV: Chipclaw - air pocket cave, underwater 2"
clothesclaw_flotsamvale_APabove = "FV: Clothesclaw - air pocket cave, above water"
hairclaw_flotsamvale_APabove2 = "FV: Hairclaw - air pocket cave, above water 2"
paperclaw_flotsamvale_shippingdock = "FV: Paperclaw - under shipping port dock"
hairclaw_flotsamvale_trashpile = "FV: Hairclaw - trash pile, past shipping dock"
clothesclaw_flotsamvale_consortium = "FV: Clothesclaw - top of cage, before miniboss"
paperclaw_flotsamvale_billboard = "FV: Paperclaw - behind license plate billboard, near Scuttleport"
chipclaw_flotsamvale_consortiumgrapple = "FV: Chipclaw - past miniboss"
clothesclaw_flotsamvale_northfish = "FV: Clothesclaw - spearfishing, gunk lake, north"
breadclaw_flotsamvale_westfish = "FV: Breadclaw - spearfishing, gunk lake, west"
clothesclaw_flotsamvale_northshorefish = "FV: Clothesclaw - spearfishing, gunk lake, northern shore"
clothesclaw_flotsamvale_southfish = "FV: Clothesclaw - spearfishing, gunk lake, south of miniboss"
hairclaw_flotsamvale_APfish = "FV: Hairclaw - spearfishing, gunk lake near air pocket cave"
chipclaw_flotsamvale_consortiumfish = "FV: Chipclaw - spearfishing, past miniboss"
paperclaw_flotsamvale_uppervale = "FV: Paperclaw - near upper Flotsam Vale"
breadclaw_flotsamvale_gunkfish = "FV: Breadclaw - spearfishing, dock"
clothesclaw_flotsamvale_gunkfish = "FV: Clothesclaw - spearfishing, dock"
hairclaw_flotsamvale_gunkfish = "FV: Hairclaw - spearfishing, near bridge"
chipclaw_flotsamvale_gunkfish = "FV: Chipclaw - spearfishing, near bridge"


breadclaw_scuttleport_cubby = "SP: Breadclaw - cubby, entrance"
clothesclaw_scuttleport_cubby = "SP: Clothesclaw - cubby, entrance"
hairclaw_scuttleport_cubbies = "SP: Hairclaw - next to cubby, entrance"
breadclaw_scuttleport_grate = "SP: Breadclaw - grate left of first room"
hairclaw_scuttleport_magnet = "SP: Hairclaw - after first magnet"
clothesclaw_scuttleport_electriccrab = "SP: Clothesclaw - near electric long-legged crab"
clothesclaw_scuttleport_trashisland = "SP: Clothesclaw - trash island, under second magnet dropoff"
paperclaw_scuttleport_elevator = "SP: Paperclaw - elevator, under second magnet dropoff"
hairclaw_scuttleport_rooftopedge = "SP: Hairclaw - edge of first rooftop"
hairclaw_scuttleport_rooftoptrash = "SP: Hairclaw - trash blocks, first rooftop"
hairclaw_scuttleport_survivorcamp = "SP: Hairclaw - edge of Survivors Camp rooftop"
clothesclaw_scuttleport_npccrab = "SP: Clothesclaw - balcony next to NCP crab"
chipclaw_scuttleport_survivorcamp = "SP: Chipclaw - inside Survivor's Camp building"
clothesclaw_scuttleport_magrail1 = "SP: Clothesclaw - Mag-Rail Platform building"
clothesclaw_scuttleport_magrail2 = "SP: Clothesclaw - Mag-Rail Platform building 2"
hairclaw_scuttleport_magrailroof1 = "SP: Hairclaw - Mag-Rail Platform building rooftop"
paperclaw_scuttleport_magrail = "SP: Paperclaw - trashblocks, Mag-Rail Platform building rooftop"
hairclaw_scuttleport_magrailroof2 = "SP: Hairclaw - Mag-Rail Platform building rooftop 2"
chipclaw_scuttleport_magrail = "SP: Chipclaw - Mag-Rail Platform building rooftop"
hairclaw_scuttleport_magrail = "SP: Hairclaw - Mag-Rail Platform building"
chipclaw_scuttleport_propanebridge = "SP: Chipclaw - inside propane tank bridge"
clothesclaw_scuttleport_propanebridge = "SP: Clothesclaw - inside propane tank bridge"

paperclaw_pinbarge = "PB: Paperclaw"
stapleclaw_pinbarge = "PB: Stapleclaw"

stapleclaw_unfathom_eastclam = "UF: Stapleclaw - clam on path, east"
paperclaw_unfathom_vcr = "UF: Paperclaw - under VCR"
paperclaw_unfathom_glowstickclam = "UF: Paperclaw - clam, past red glowstick"
clothesclaw_unfathom_cassette = "UF: Clothesclaw - cassette tape, near Nemma shortcut"
clothesclaw_unfathom_pinbarge1 = "UF: Clothesclaw - near Pinbarge shipwreck"
clothesclaw_unfathom_pinbarge2 = "UF: Clothesclaw - near Pinbarge shipwreck 2"
paperclaw_unfathom_pinbarge = "UF: Paperclaw - near Pinbarge shipwreck"
paperclaw_unfathom_shortcut = "UF: Paperclaw - near second shortcut"
paperclaw_unfathom_glowstick = "UF: Paperclaw - glowstick, northease of Pinbarge"
paperclaw_unfathom_northeastbarge = "UF: Paperclaw - ledge, far northeast of Pinbarge"
clothesclaw_unfathom_shortcut = "UF: Clothesclaw - ledge near second shortcut, north"
chipclaw_unfathom_shortcuthill = "UF: Chipclaw - hill near second shortcut, north"
hairclaw_unfathom_shortcut = "UF: Hairclaw - near second shortcut, north"
hairclaw_unfathom_styrofoam = "UF: Hairclaw - styrofoam near second shortcut, north"

clothesclaw_plains_entrance = "AP: Clothesclaw - near entrance"
hairclaw_plains_entrance = "AP: Hairclaw - near entrance, north"
hairclaw_plains_shortcut = "AP: Hairclaw - near shortcut"
stapleclaw_plains_fish = "AP: Stapleclaw - spearfishing, near shortcut, southeast"

paperclaw_oldocean_northhouse = "OO: Paperclaw - styrofoam house near shortcut, north"
hairclaw_oldocean_northhouse = "OO: Hairclaw - styrofoam house near shortcut, north"
paperclaw_oldocean_mainshortcut = "OO: Paperclaw - near shortcut"
paperclaw_oldocean_islandhouse = "OO: Paperclaw - styrofoam house, second island"
clothesclaw_oldocean_bubbles = "OO: Clothesclaw - below first bubble jumps"
paperclaw_oldocean_shortcut = "OO: Paperclaw - near large shortcut"
hairclaw_oldocean_shortcut = "OO: Hairclaw - near large shortcut"
paperclaw_oldocean_southhouse = "OO: Paperclaw - styrofoam house, second island, south"
carclaw_oldocean_islandclam = "OO: Carclaw - clam on second island"
stapleclaw_oldocean_brokenbridge = "OO: Stapleclaw - broken bridge to city"
paperclaw_oldocean_scourcrab = "OO: Paperclaw - ledge near scour crab"
hairclaw_oldocean_northentrance = "OO: Hairclaw - city entrance, north"
hairclaw_oldocean_cityentrance = "OO: Hairclaw - city entrance"
paperclaw_oldocean_northentrance = "OO: Paperclaw - city entrance, north"
hairclaw_oldocean_citygates = "OO: Hairclaw - past City Gates snail shell"
paperclaw_oldocean_citygates = "OO: Paperclaw - past City Gates snail shell"
clothesclaw_oldocean_citygates = "OO: Clothesclaw - near City Gates snail shell, southeast"
clothesclaw_oldocean_seafoam = "OO: Clothesclaw - near seafoam cans"
carclaw_oldocean_seafoam = "OO: Carclaw - clam, near seafoam cans"
hairclaw_oldocean_brokenshell = "OO: Hairclaw - ledge, inside broken shell"
breadclaw_oldocean_teethtrap = "OO: Breadclaw - teeth trap, hallway"
hairclaw_oldocean_woodplank = "OO: Hairclaw - drop down to wooden planks"
carclaw_oldocean_scourcrab = "OO: Carclaw - top of building, behind scour crab"
paperclaw_oldocean_eastsnail = "OO: Paperclaw - near snail shell, east"
hairclaw_oldocean_scourcrab = "OO: Hairclaw - platform near scour crab"
paperclaw_oldocean_scourledge = "OO: Paperclaw - ledge near scour crab"
stapleclaw_oldocean_parkour = "OO: Stapleclaw - staircase, near long parkour section"
stapleclaw_oldocean_middlebuilding = "OO: Stapleclaw - middle building, drop down"
carclaw_oldocean_eastbuilding = "OO: Carclaw - outside building, east"
carclaw_oldocean_camtscha = "OO: Carclaw - outside boss arena"
stapleclaw_oldocean_eastbuilding = "OO: Stapleclaw - ledge outside building, east"
carclaw_oldocean_camtschapath = "OO: Carclaw - pathway to boss arena"
stapleclaw_oldocean_camtschastairs = "OO: Stapleclaw - large staircase before boss arena"
carclaw_oldocean_middlebuilding = "OO: Carclaw - clam, middle building"

# upgrade item locations
bloodstar_shallows_help = "Bloodstar Limb (Central Shallows - Help a Crab)" # the bloodstar limb acquired from helping the surrounded crab in the shallows
bloodstar_shallows_parkour = "Bloodstar Limb (Central Shallows - Parkour on Small Islands)"
bloodstar_shallows_bridge = "Bloodstar Limb (Central Shallows - Ledge Near Red Flip-Flop Bridge)"
bloodstar_shallows_clam = "Bloodstar Limb (Central Shallow - Southwest Sandcastle Clam)"

kelpsprout_snailcave_elevator = "Heartkelp Sprout (Moon Snail's Cave - Moon Jelly Elevators)"
bloodstar_snailcave_platoon = "Bloodstar Limb (Moon Snail's Cave - Just Before Platoon Pathfinder)"

bloodstar_slacktide_clam = "Bloodstar Limb (Slacktide - Clam Above Duchess's Chamber)" # bloodstar limb found by grappling up in the area before you fight the duchess and opening the clam

stainlessrelic_reefsedge_coral = "Stainless Relic (Reef's Edge - Flat Coral Near Entrance)"

bloodstar_sandsbetween_playground = "Bloodstar Limb (The Sands Between - Cup House in Playground Town near Flotsam)"
tacklepouch_sandsbetween_cooler = "Tackle Pouch (The Sands Between - Cooler on Southern Edge)"
bloodstar_sandsbetween_southwestcentral = "Bloodstar Limb (The Sands Between - Rocks Southwest of Central Vista)"
oldworldwhorl_sandsbetween_mantispitfall = "Old World Whorl (The Sands Between - Mantis Block Pitfall North of Central Vista)"
stainlessrelic_sandsbetween_eelectrocute = "Stainless Relic (The Sands Between - On Electric Crab Platform)"
tacklepouch_sandsbetween_eelnorthchain = "Tackle Pouch (The Sands Between - Eelectrocute Crab North of Chains)"
kelpsprout_sandsbetween_southeelside = "Hearkelp Sprout (The Sands Between - South Eelectrocute Path, Green Coral Side Path)"

bloodstar_postpag_anchorswarm = "Bloodstar Limb (Post Pagurus - Crab Swarm Near Anchor)"

stainlessrelic_ridge_overlook = "Stainless Relic (Secluded Ridge - Plate on Ridge Overlook)"
kelpsprout_ridge_eelend = "Heartkelp Sprout (Secluded Ridge - End of Eelectrocute Path, Near Bobbit)"
oldworldwhorl_ridge_ncliff = "Old World Whorl (Secluded Ridge - North Cliff Clam)"
oldworldwhorl_ridge_eelclam = "Old World Whorl (Secluded Ridge - Eelectrocute Clam)"

oldworldwhorl_grovemain_southclam = "Old World Whorl (Expired Grove Main - South Clam)"
bloodstar_grovemain_waterfall = "Bloodstar Limb (Expired Grove Main - Behind Gunk Waterfall)"
kelpsprout_grovemain_carts = "Heartkelp Sprout (Expired Grove Main - Top of Shopping Cart Buildings)"

bloodstar_grovevillage_carton = "Bloodstar Limb (Expired Grove Village - In Upper South Milk Carton)"
tacklepouch_grovevillage_clam = "Tackle Pouch (Expired Grove Village - Clam Near Cave Shortcut)"
stainlessrelic_grovevillage_clam = "Stainless Relic (Expired Grove Village - Clam in Hammer Crab Cave)"
oldworldwhorl_grovevillage_topoda = "Old World Whorl (Expired Grove Village - Post-Topoda Mantis Block)"

bloodstar_flotsamvale_submerged = "Bloodstar Limb (Flotsam Vale - North Submerged Butane Tank)"
oldworldwhorl_flotsamvale_cavepath = "Old World Whorl (Flotsam Vale - Cave Path to Upper Flotsam Vale Clam)"
oldworldwhorl_flotsamvale_snail = "Old World Whorl (Flotsam Vale - Upper Flotsam Vale Past Snail Shell)"
bloodstar_flotsamvale_craneclam = "Bloodstar Limb (Flotsam Vale - Clam on Crane Platform Near Mailbox)"
tacklepouch_flotsamvale_waterfall = "Tacklepouch (Flotsam Vale - Behind Waterfall)"

stainlessrelic_scuttleport_clam = "Stainless Relic (Scuttleport - Clam on Left Path After First Magnet)"
bloodstar_scuttleport_magrailclam = "Bloodstar Limb (Scuttleport - Clam on Mag-Rail Platform Building Rooftop)"
stainlessrelic_scuttleport_magrail = "Stainless Relic (Scuttleport - Mag-Rail Platform Building)"
stainlessrelic_scuttleport_propanebridge = "Stainless Relic (Scuttleport - Building Past Propane Tank Bridge)"
oldworldwhorl_scuttleport_eelectrocute = "Old World Whorl (Scuttleport - Eelectrocute Room in Survivor's Camp Building)"

bloodstar_unfathom_eastpath = "Bloodstar Limb (The Unfathom - Path to The East)"
bloodstar_unfathom_shortcut = "Bloodstar Limb (The Unfathom - Past Second Shortcut)"

stainlessrelic_plains_sponges = "Stainless Relic (Abyssal Plains - Across Bouncy Sponges East of Petroch)"
stainlessrelic_plains_snipers = "Stainless Relic (Abyssal Plains - Between Giant Sniper Crabs)"
oldworldwhorl_plains_shortcut = "Old World Whorl (Abyssal Plains - Southeast of Shortcut)"
bloodstar_plains_shortcutclam = "Bloodstar Limb (Abyssal Plains - Clam in Cave East of Shortcut)"
kelpsprout_plains_grappleclam = "Hearkelp Sprout (Abyssal Plains - Clam East of Petroch)"
tacklepouch_plains_grapplesnail = "Tackle Pouch (Abyssal Plains - Across Grapple Hooks by Snail Shell)"

oldworldwhorl_oldocean_ledgeclam = "Old World Whorl (The Old Ocean - Clam on Ledge North of Snail Shell)"
bloodstar_oldocean_brokenbridge = "Bloodstar Limb (The Old Ocean - Under Broken Bridge to City)"
bloodstar_oldocean_citygates = "Bloodstar Limb (The Old Ocean - Drop Down Southeast of City Gates Snail Shell)"
stainlessrelic_oldocean_citywall = "Stainless Relic (The Old Ocean - Inside City Walls)"
kelpsprout_oldocean_parkourclam = "Hearkelp Sprout (The Old Ocean - Clam Past Seafoam Parkour)"
stainlessrelic_oldocean_styrofoamclam = "Stainless Relic (The Old Ocean - Clam on Top of Styrofoam Building)"
bloodstar_oldocean_easternbuilding = "Bloodstar Limb (The Old Ocean - Inside Eastern Building)"
oldworldwhorl_oldocean_easternclam = "Old World Whorl (The Old Ocean - Clam in Eastern Building)"

# consumable item locations
barbedhook_reefsedge_undercoral = "Barbed Hook (Reef's Edge - Under Coral Near Shot Glass Crab)"
barbedhook_reefsedge_seahorses = "Barbed Hook (Reef's Edge - Coral Near Two Seahorses)"
barbedhook_reefsedge_shortcut = "Barbed Hook (Reef's Edge - Near Shortcut)"
barbedhook_reefsedge_cliff = "Barbed Hook (Reef's Edge - North Facing Cliff Near Seahorse)"

barbedhook_newcarcinia_citycenter = "Barbed Hook (New Carcinia - Top of Building in City Center)"

barbedhook_sandsbetween_centralvista = "Barbed Hook (The Sands Between - Central Vista Near Safety Tube)"
barbedhook_sandsbetween_southernreef = "Barbed Hook (The Sands Between - Pizza Box near Southern Reef)"
barbedhook3_sandsbetween_cooler = "Barbed Hook x3 (The Sands Between - North of Cooler)"
barbedhook_sandsbetween_fence = "Barbed Hook (The Sands Between - Fence Southwest of Cooler)"
barbedhook_sandsbetween_spire = "Barbed Hook (The Sands Between - Top of Spire Near Grove Entrance)"
barbedhook_sandsbetween_southcentral = "Barbed Hook (The Sands Between - South of Central Vista, Near Fence)"
barbedhook_sandsbetween_bobbitbase = "Barbed Hook (The Sands Between - Base of Bobbit Hill)"
barbedhook_sandsbetween_northofridge = "Barbed Hook (The Sands Between - North of Secluded Ridge)"
barbedhook_sandsbetween_southeel = "Barbed Hook (The Sands Between - South Eelectrocute Path Large Island)"
barbedhook_sandsbetween_southeelshellsplitter = "Barbed Hook (The Sands Between - South Eelectrocute Path Near Shellsplitter)"

barbedhook_postpag_nechain = "Barbed Hook (Post Pagurus - Near Northeastern Chain)"
barbedhook_postpag_echain = "Barbed Hook (Post Pagurus - East of Chains)"
barbedhook_postpag_echainpreserver = "Barbed Hook (Post Pagurus - Near Preserver East of Chains)"
barbedhook_postpag_necentral = "Barbed Hook (Post Pagurus - Rocks North-East of Central Vista)"
barbedhook_postpag_nwridge = "Barbed Hook (Post Pagurus - Rocks North-West of Ridge Overlook)"
barbedhook_postpag_neeelpath = "Barbed Hook (Post Pagurus - Fence Near North-East Eelectrocute Path)"
barbedhook_postpag_ridgeentrance = "Barbed Hook (Post Pagurus - Near Secluded Ridge Entrance)"
barbedhook_postpag_wplayground = "Barbed Hook (Post Pagurus - West of Playground)"
barbedhook_postpag_swcentral = "Barbed Hook (Post Pagurus - South-West of Central Vista)"

barbedhook_ridge_near = "Barbed Hook (Secluded Ridge - Near Secluded Ridge Moon Snail Shell)"
barbedhook_ridge_overlookpath = "Barbed Hook (Secluded Ridge - Path to Ridge Overlook)"
sharkegg_ridge_broomspire = "Shark Egg (Secluded Ridge - Broom Spire Peak)"

barbedhook_trashbin_eelgrapple = "Barbed Hook (Trashbin Plateau - Eelectrocute Grapple Path)"

barbedhook_grovemain_sniper = "Barbed Hook (Expired Grove Main - Next to Sniper Crab)"
barbedhook_grovemain_riverledge = "Barbed Hook (Expired Grove Main - Ledge Near Gunk River)"
barbedhook_grovemain_riversand = "Barbed Hook (Expired Grove Main - In Sand Near Gunk River)"
barbedhook_grovemain_lichenthrope = "Barbed Hook (Expired Grove Main - Behind Diseased Lichenthrope)"
barbedhook_grovemain_lichenthropeeast = "Barbed Hook (Expired Grove Main - Ledge East of Lichenthrope)"
barbedhook_grovemain_sodacans = "Barbed Hook (Expired Grove Main - Crushed Soda Cans)"
barbedhook_grovemain_acrossriver = "Barbed Hook (Expired Grove Main - Ledge Across Gunk River)"
barbedhook_grovemain_afternets = "Barbed Hook (Expired Grove Main - Ledge After Grapple Nets)"
barbedhook_grovemain_cartledge = "Barbed Hook (Expired Grove Main - Ledge After Shopping Cart)"
barbedhook_grovemain_cartledgebottle = "Barbed Hook (Expired Grove Main - Bottles on Ledge After Shopping Cart)"
barbedhook_grovemain_paperplate = "Barbed Hook (Expired Grove Main - Paper Plate Near River)"
barbedhook_grovemain_oildrum = "Barbed Hook (Expired Grove Main - Main Pathway Around Oil Drum)"
barbedhook_grovemain_canopy = "Barbed Hook  (Expired Grove Main - Carton Canopy)"
barbedhook_grovemain_drumtop = "Barbed Hook (Expired Grove Main - Near Top of Oil Drum)"
barbedhook_grovemain_carts = "Barbed Hook (Expired Grove Main - Shopping Cart Buildings)"
sharkegg_grovemain_mantis = "Shark Egg (Expired Grove Main - Mantis Block on Left Path)"

barbedhook_grovevillage_heikea = "Barbed Hook (Expired Grove Village - In Cave After Heikea)"
barbedhook_grovevillage_cartfish = "Barbed Hook (Expired Grove Village - Hidden Fishing Near Shopping Cart Mantis Block)"
barbedhook_grovevillage_riveroil = "Barbed Hook (Expired Grove Village - River Fishing After Oil Drum)"
barbedhook_grovevillage_bottles = "Barbed Hook (Expired Grove Village - Bottles Before Heikea)"
barbedhook_grovevillage_crabs = "Barbed Hook (Expired Grove Village - Between Two Crabs)"
barbedhook_grovevillage_centercarton = "Barbed Hook (Expired Grove Village - In Center Milk Carton)"
barbedhook_grovevillage_corpse = "Barbed Hook (Expired Grove Village - In Center Near Corpse)"
barbedhook_grovevillage_path = "Barbed Hook (Expired Grove Village - On Center Path)"
barbedhook_grovevillage_Ncarton = "Barbed Hook (Expired Grove Village - In North Milk Carton)"
barbedhook_grovevillage_SWcarton = "Barbed Hook (Expired Grove Village - In South West Milk Carton)"
sharkegg_grovevillage_sniper = "Shark Egg (Expired Grove Village - Near Village Sniper)"
barbedhook_grovevillage_boat = "Barbed Hook (Expired Grove Village - Under Heikea Boat)"
barbedhook_grovevillage_butter = "Barbed Hook (Expired Grove Village - Butter Carton in Cave)"
barbedhook_grovevillage_above1 = "Barbed Hook (Expired Grove Village - Above Village 1)"
barbedhook_grovevillage_above2 = "Barbed Hook (Expired Grove Village - Above Village 2)"
barbedhook_grovevillage_above3 = "Barbed Hook (Expired Grove Village - Above Village 3)"
barbedhook_grovevillage_ornament = "Barbed Hook (Expired Grove Village - In Bottle After Ornament Parkour)"
barbedhook_grovevillage_hammer = "Barbed Hook (Expired Grove Village - In Hammer Crab Cave)"
barbedhook_grovevillage_dock = "Barbed Hook (Expired Grove Village - Dock Fishing Spot 1)"

barbedhook_flotsamvale_entranceledge = "Barbed Hook (Flotsam Vale - Ledge Near Main Entrance)"
barbedhook_flotsamvale_entrancerocks = "Barbed Hook (Flotsam Vale - Rocks Near Main Entrance)"
barbedhook_flotsamvale_northbeach = "Barbed Hook (Flotsam Vale - Beach North of Main Entrance)"
barbedhook_flotsamvale_butaneisland = "Barbed Hook (Flotsam Vale - Butane Tank Island East of Main Entrance)"
barbedhook_flotsamvale_snailshell = "Barbed Hook (Flotsam Vale - Upper Flotsam Vale Near Snail Shell)"
barbedhook_flotsamvale_wooddeck = "Barbed Hook (Flotsam Vale - Wooden Deck Above Propane Tank)"
barbedhook_flotsamvale_woodplatform1 = "Barbed Hook (Flotsam Vale - Wooden Platform Above Sludge Steamroller 1)"
barbedhook_flotsamvale_woodplatform2 = "Barbed Hook (Flotsam Vale - Wooden Platform Above Sludge Steamroller 2)"
barbedhook_flotsamvale_westbutane = "Barbed Hook (Flotsam Vale - Butane Tanks South of Sludge Steamroller)"
barbedhook_flotsamvale_mailbox = "Barbed Hook (Flotsam Vale - Butane Tanks Southwest of Mailbox)"
barbedhook_flotsamvale_APunder1 = "Barbed Hook (Flotsam Vale - Air Pocket Cave Underwater 1)"
barbedhook_flotsamvale_APunder2 = "Barbed Hook (Flotsam Vale - Air Pocket Cave Underwater 2)"
barbedhook_flotsamvale_APabove = "Barbed Hook (Flotsam Vale - Air Pocket Cave Above Water)"
barbedhook_flotsamvale_shippingsnail = "Barbed Hook (Flotsam Vale - Behind Shipping Port Snail Shell)"
barbedhook_flotsamvale_shippingbutane = "Barbed Hook (Flotsam Vale - Butane Tank at Shipping Port)"
barbedhook_flotsamvale_trashpile = "Barbed Hook (Flotsam Vale - Trash Pile Past Shipping Dock)"
barbedhook_flotsamvale_consortiumcage = "Barbed Hook (Flotsam Vale - Top of Cage Next to Consortium)"
barbedhook_flotsamvale_consortium = "Barbed Hook (Flotsam Vale - In Front of Consortium)"
barbedhook_flotsamvale_snailfish = "Barbed Hook (Flotsam Vale - Upper Flotsam Vale Fishing Near Snail Shell)"
barbedhook_flotsamvale_westfish = "Barbed Hook (Flotsam Vale - Gunk Lake Fishing West of Sludge Steamroller)"
barbedhook_flotsamvale_behindcubby = "Barbed Hook (Flotsam Vale - Behind Cubby)"
barbedhook_flotsamvale_gunkfish = "Barbed Hook (Flotsam Vale - Gunk Fishing Near Dock)"
barbedhook_flotsamvale_sludgefish = "Barbed Hook (Flotsam Vale - Gunk Fishing Near Sludge Steamroller)"


barbedhook_scuttleport_cubby = "Barbed Hook (Scuttleport - Cubby in First Room)"
barbedhook_scuttleport_magnet = "Barbed Hook (Scuttleport - Platform Next to First Magnet)"
barbedhook_scuttleport_sorting = "Barbed Hook (Scuttleport - In Front of Sorting Chamber Snail Shell)"
barbedhook_scuttleport_magnetdropoff1 = "Barbed Hook (Scuttleport - Platform Under Second Magnet Dropoff 1)"
barbedhook_scuttleport_trashisland = "Barbed Hook (Scuttleport - Trash Island Under Second Magnet Dropoff)"
barbedhook_scuttleport_magnetdropoff2 = "Barbed Hook (Scuttleport - Platform Under Second Magnet Dropoff 2)"
barbedhook_scuttleport_trashblock = "Barbed Hook (Scuttleport - Top of Trash Block on Survivor's Camp Rooftop)"
barbedhook_scuttleport_magrail1 = "Barbed Hook (Scuttleport - Mag-Rail Platform Building 1)"
barbedhook_scuttleport_magrail2 = "Barbed Hook (Scuttleport - Mag-Rail Platform Building 2)"
barbedhook_scuttleport_magrailroof = "Barbed Hook (Scuttleport - Mag-Rail Platform Building Rooftop)"
barbedhook_scuttleport_magrail3 = "Barbed Hook (Scuttleport - Mag-Rail Platform Building 3)"
barbedhook_scuttleport_propanebridge = "Barbed Hook (Scuttleport - Inside Propane Tank Bridge)"
barbedhook_scuttleport_afterbridge = "Barbed Hook (Scuttleport - Past Propane Tank Bridge)"
barbedhook_scuttleport_propaneroof1 = "Barbed Hook (Scuttleport - Rooftop Past Propane Tank Bridge 1)"
barbedhook_scuttleport_propaneroof2 = "Barbed Hook (Scuttleport - Rooftop Past Propane Tank Bridge 2)"

barbedhook_pinbarge1 = "Barbed Hook (Pinbarge 1)"
barbedhook_pinbarge2 = "Barbed Hook (Pinbarge 2)"

barbedhook_unfathom_mimic = "Barbed Hook (The Unfathom - Left of First Mimic)"
barbedhook_unfathom_mimichill = "Barbed Hook (The Unfathom - On a Hill After First Mimic)"

barbedhook_oldocean_northwesthouse = "Barbed Hook (The Old Ocean - Styrofoam House Northwest of Snail Shell)"
barbedhook_oldocean_southhouse = "Barbed Hook (The Old Ocean - Styrofoam House South of Second Island)"
barbedhook_oldocean_secondisland = "Barbed Hook (The Old Ocean - Middle of Second Island)"
barbedhook_oldocean_brokenbridge1 = "Barbed Hook (The Old Ocean - On Broken Bridge to City 1)"
barbedhook_oldocean_brokenbridge2 = "Barbed Hook (The Old Ocean - On Broken Bridge to City 2)"
barbedhook_oldocean_entrance = "Barbed Hook (The Old Ocean - East of City Entrance)"
barbedhook_oldocean_citygates = "Barbed Hook (The Old Ocean - Platform Past City Gates Snail Shell)"
sharkegg_oldocean_citygates = "Shark Egg (The Old Ocean - Southeast of City Gates Snail Shell)"
barbedhook_oldocean_chitan = "Barbed Hook (The Old Ocean - Southeast of Snail Shell Nearby Chitan)"
barbedhook_oldocean_eastsnail = "Barbed Hook (The Old Ocean - East of Snail Shell)"
barbedhook_oldocean_easternbuilding = "Barbed Hook (The Old Ocean - Outside Eastern Building)"
barbedhook_oldocean_middlebuilding = "Barbed Hook (The Old Ocean - Outside Middle Building)"

# stowaway item locations
siphonophore_shallows_westwall = "Siphonophore (Central Shallows - Along West Wall)" # siphonophore stowaway found in the shallow
seastar_shallows_eastledge = "Seastar (Central Shallows - East Ledge Behind Comb Crab)"
whelk_shallows_dune = "Whelk (Central Shallows - Sand Dune Near Flip-Flop Bridge)"
sponge_shallows_puffer = "Sponge (Central Shallows - East Ledge Near Pufferfish)"
anothercrab_shallows_pillar = "Another Crab (Central Shallows - Tall Pillar Near Royal Shellsplitter)"
sanddollar_shallows_arch = "Sand Dollar (Central Shallows - South Arch Wall)"
mussel_shallows_southwestcastlefish = "Mussel (Central Shallows - Dig Spot Near Southwest Sandcastle)"
anemone_shallows_southwestcastlehiddenfishing = "Anemone (Central Shallows - Hidden Fishing on South-Eastern Wall of Castle on South-Western Plateau)"
razorblade_shallows_slacktidebottlefishing = "Razor Blade (Central Shallows - Fishing South West of Slacktide Near Bottles)"
anemone_shallows_umbrellafishing = "Anemone [Stowaway] (Central Shallow - Fishing West of Umbrella)"

limpet_slacktide_stairs = "Limpet (Slacktide - Stairs Left of Main Hallway)" # limpet up the stairs to the left of the main hallway to the duchess in slacktide
seastar_slacktide_grappleroom = "Seastar (Slacktide - Top of Fishing Line Room)" # seastar found by grappling up in the room where the fishing line is found
barnacle_slacktide_bigurchin = "Barnacle (Slacktide - After Big Urchin Spiral Staircase)" # barnacle found after running up the staircase where the giant urchin rolls down toward the player

limpet_snailcave_jelly = "Limpet (Moon Snail's Cave - Ride the First Moon Jelly)"

mussel_slacktide_fortentrance =  "Mussel (Slacktide - Southwest Fort Entrance)" # mussel at the entrance of slacktide after it is corrupted
anemone_slacktide_fortwall = "Anemone (Slacktide - South Fort Wall)" # anemone found on top of the fort wall toward the south
whelk_slacktide_turrettop = "Whelk (Slacktide - Center Castle Turret Top)" # whelk found after climbing up the castle turret in the center of slacktide
rustynail_slacktide_bigurchin = "Rusty Nail (Slacktide - Big Urchin Staircase Grapple Point)"

seastar_reefsedge_crabs = "Seastar (Reef's Edge - Surrounded by Crabs)"
seastarplus_reefsedge_pole = "Sea Star+ (Reef's Edge - Top of Large Hammer Crab Pole)"
whelkplus_reefsedge_sponge = "Whelk+ (Reef's Edge - Near Orange Coral and Sponge)"

limpet_newcarcinia_entrance = "Limpet (New Carcinia - Top of Cardboard Buildings Near Entrance)"
rustynail_newcarcinia_hammerhead = "Rusty Nail (New Carcinia - On Top of Hammerhead Toolbox)"

sanddollar_newcarcinia_hammerhead = "Sand Dollar (New Carcinia - Flat Coral Near/Above Hammerhead)"

phytoplankton_sandsbetween_centralvista = "Phytoplankton (The Sands Between - Central Vista Center Tunnel)"
anemone_sandsbetween_centralvista = "Anemone (The Sands Between - Central Vista Top)"
anemone_sandsbetween_playground = "Anemone (The Sands Between - Sinkhole filled with Crabs near Playground Town)"
rustynail_sandsbetween_fence = "Rusty Nail (The Sands Between - Near Fence and Rock West of Playground Town)"
googlyeye_sandsbetween_pizza = "Googly Eye (The Sands Between - Microplastics near Southern Pizza Box)"
siphonophore_sandsbetween_cooler = "Siphonophore (The Sands Between - Rocks Southwest of Cooler aka Old Pag Quick Kill Spot)"
limpet_sandsbetween_anchor = "Limpet (The Sands Between - Near Two Bobbit Worms on East Side near Anchor)"
anemone_sandsbetween_chains = "Anemone (The Sands Between - Sinkhole by West Chains)"
fredrick_sandsbetween_fredrick = "Fredrick (The Sands Between - Fredrick's Grave by West Chains)"
anothercrab_sandsbetween_chains = "Another Crab (The Sands Between - Under Chain on West Side)"
mussel_sandsbetween_anchor = "Mussel (The Sands Between - Rocks Below Anchor on West Side)"
barnacle_sandsbetween_northeast = "Barnacle (The Sands Between - Rocks Northeast of Central Vista)"
salp_sandsbetween_northeast = "Salp (The Sands Between - Sinkhole near Rocks Northeast of Central Vista)"
rustynailplus_sandsbetween_centralvista = "Rusty Nail+ (The Sands Between - Mantis Block near Central Vista)"
seastarplus_sandsbetween_flotsam = "Sea Star+ (The Sands Between - Mantis Block near Flotsam Vale Entrance)"
seaslug_sandsbetween_crabrave = "Sea Slug (The Sands Between - Mantis Block below Crab Rave)"
whelk_sandsbetween_crabrave = "Sea Slug (The Sands Between - Mantis Block below Crab Rave)"
sinkerplus_sandsbetween_northridgemantis = "Sinker+ (The Sands Between - Mantis Block North of Secluded Ridge)"
limpetplus_sandsbetween_grovemantis = "Limpet+ (The Sands Between - Mantis Block at Grove Entrance)"
lumpsuckerplus_sandsbetween_anchor = "Lumpsucker+ (The Sands Between - On the anchor, after the electric crab)"
sinkerplus_sandsbetween_southeel = "Sinker+ (The Sands Between - South Eelectrocute Path)"
musselplus_sandsbetween_southeel = "Mussel+ (The Sands Between - South Eelectrocute Path First Jump)"
oyster_sandsbetween_southeelashtray = "Oyster (The Sands Between - South Eelectrocute Path Large Island Ashtray)"
mussel_sandsbetween_bobbitfish = "Mussel (The Sands Between - Fishing Near Bobbit Hill)"
barnacle_sandsbetween_bobbitfish = "Barnacle (The Sands Between - Fishing On Bobbit Hill 2nd Layer)"
whelkplusplus_sandsbetween_southeelpeak = "Whelk++ (The Sands Between - South Eelectrocute Path First Island Peak)"
salpplus_sandsbetween_groveeel = "Salp+ (The Sands Between - Eelectrocute Path Near Grove Small Island)"
usedbandage_sandsbetween_groveeel = "Used Bandage (The Sands Between - Eelectrocute Path Near Grove)"

limpet_ridge_ncliffkelp = "Limpet (Secluded Ridge - North Cliff Hidden in Kelp)"
sanddollar_ridge_broom = "Sanddollar (Secluded Ridge - Near Broom)"
musselplus_ridge_togo = "Mussel+ (Secluded Ridge - Western Cliff To Go Box)"
siphonophoreplus_ridge_pitfall = "Siphonophore+ (Secluded Ridge - Pitfall)"
anemoneplus_ridge_eel = "Anemone+ (Secluded Ridge - Eelectrocute)"
cockle_ridge_eelfish = "Cockle (Secluded Ridge - Fishing on Eelectrocute Path)"
bobber_ridge_broomspire = "Bobber (Secluded Ridge - Broom Spire Climb)"

cockle_trashbin_peak = "Cockle (Trashbin Plateau - Peak)"
sinker_trashbin_peak = "Sinker (Trashbin Plateau - Peak)"
smallbattery_trashbin_mantis = "Small Battery (Trashbin Plateau - Mantis Block)"
googlyeye_trashbin_pineapple = "Googly Eye (Trashbin Plateau - Pineapple)"

barnacle_grovemain_colander = "Barnacle (Expired Grove Main - On Top of Colander)"
seastar_grovemain_eastrock = "Seastar (Expired Grove Main - East Circular Rock)"
pufferquill_grovemain_sponges = "Puffer Quill (Expired Grove Main - Cross Sponge Islands)"
limpet_grovemain_sodacan = "Limpet (Expired Grove Main - Soda Can Stepping Stones)"
lumpsucker_grovemain_canopy = "Lumpsucker (Expired Grove Main - Carton Canopy)"
sharktooth_grovemain_pizza = "Shark Tooth (Expired Grove Main - Under Pizza Box)"
anothercrab_grovemain_sniper = "Another Crab (Expired Grove Main - Beginning of Sniper Path)"
contactlens_grovemain_carts = "Contact Lens (Expired Grove Main - Behind Shopping Cart Buildings)"
cottonball_grovemain_mantis = "Cotton Ball (Expired Grove Main - Mantis Block on Oil Drum Path)"
mussel_grovemain_fishing = "Mussel (Expired Grove Main - Fishing by Entrance)"
sponge_grovemain_fishing = "Sponge (Expired Grove Main - Fishing by Crystal Parkour)"
oyster_grovemain_fishing = "Oyster (Expired Grove Main - River Fishing Under Bridge)"
limpet_grovemain_fishing = "Limpet (Expired Grove Main - River Fishing Before Lichenthrope)"

anemone_grovevillage_fishing = "Anemone (Expired Grove Village - River Fishing Near Cart Mantis Block)"
phytoplanktonplus_grovevillage_upsidedown = "Phytoplankton+ (Expired Grove Village - Top of Upside Down village)"
wadofgum_grovevillage_gumpile = "Wad of Gum (Expired Grove Village - Gum Pile in Hammer Crab Cave)"
anemone_grovevillage_seahorse = "Anemone (Expired Grove Village - Near Seahorse)"
mussel_grovevillage_dock = "Mussel (Expired Grove Village - Dock Fishing Spot 2)"
earthworm_grovevillage_dock = "Earthworm (Expired Grove Village - Dock Fishing Spot 5)"

anemone_flotsamvale_butaneisland = "Anemone (Flotsam Vale - Butane Tank Island East of Main Entrance)"
rustynail_flotsamvale_brokenbutane = "Rusty Nail (Flotsam Vale - In Gunk Under Broken Butane Tank)"
sinker_flotsamvale_woodplatform = "Sinker (Flotsam Vale - Wooden Platform Above Sludge Steamroller)"
mussel_flotsamvale_woodplatform = "Mussel (Flotsam Vale - Wooden Platform Above Sludge Steamroller)"
rustynail_flotsamvale_steamroller = "Rusty Nail (Flotsam Vale - In Gunk Near Sludge Steamroller)"
limpet_flotsamvale_trashpile = "Limpet (Flotsam Vale - Trash Pile Near Sludge Steamroller)"
fruitsticker_flotsamvale_westbutane = "Fruit Sticker (Flotsam Vale - Butane Tanks West of Sludge Steamroller)"
seacucumber_flotsamvale_westbutane = "Sea Cucumber (Flotsam Vale - Butane Tanks West of Sludge Steamroller)"
lumpsucker_flotsamvale_shorcut = "Lumpsucker (Flotsam Vale - Ledge Below Shortcut to Map Piece)"
oyster_flotsamvale_butanemailbox = "Oyster (Flotsam Vale - Butane Tanks Southwest of Mailbox)"
seastar_flotsamvale_butanemailbox = "Seastar (Flotsam Vale - Butane Tanks Southwest of Mailbox)"
anemone_flotsamvale_APunder = "Anemone (Flotsam Vale - Air Pocket Cave Underwater)"
cockle_flotsamvale_APabove = "Cockle (Flotsam Vale - Air Pocket Cave Above Water)"
sanddollar_flotsamvale_APabove = "Sand Dollar (Flotsam Vale - Air Pocket Cave Above Water)"
anemoneplus_flotsamvale_APunder = "Anemone+ (Flotsam Vale - Air Pocket Cave Underwater)"
anothercrab_flotsamvale_mailbox = "Another Crab (Flotsam Vale - Clam Leading Up to Mailbox)"
sponge_flotsamvale_cranegrapple = "Sponge (Flotsam Vale - Crane Grapple Up Toward Expired Grove)"
seastarplus_flotsamvale_submerged = "Seastar+ (Flotsam Vale - Submerged Butane Tank Southwest of Sludge Steamroller)"
lamprey_flotsamvale_islandfish = "Lamprey (Flotsam Vale - Small Island Fishing East of Entrance)"
mussel_flotsamvale_elevatedfish = "Mussel (Flotsam Vale - Elevated Island Fishing)"
siphonophoreplus_flotsamvale_waterfall = "Siphonophore+ (Flotsam Vale - Fishing Near Waterfall)"
whelk_flotsamvale_westfish = "Whelk (Flotsam Vale - West Gunk Lake Fishing)"
anemoneplus_flotsamvale_northwestfish = "Anemone+ (Flotsam Vale - Gunk Lake Fishing Northwest of Sludge Steamroller)"
turtleshell_flotsamvale_gunkfish = "Turtle Shell Shard (Flotsam Vale - Gunk Fishing by Priest)"
lilisopod_flotsamvale_gunkfish = "Lil' Isopod (Flotsam Vale - Gunk Fishing on Docks)"
rustynail_flotsamvale_gunkfish = "Rusty Nail (Flotsam Vale - Gunk Fishing Near Blue Tower)"
barnacle_flotsamvale_gunkfish = "Barnacle (Flotsam Vale - Gunk Fishing Near Middle Tower)"

googlyeye_scuttleport_cubbies = "Googly Eye (Scuttleport - Top of Cubbies in First Room)"
seastar_scuttleport_cubbies = "Seastar (Scuttleport - Top of Cubbies in First Room)"
sanddollar_scuttleport_magnet = "Sand Dollar (Scuttleport - Path to First Magnet)"
mussel_scuttleport_magnetfish = "Mussel (Scuttleport - Fishing Next to First Magnet)"
limpet_scuttleport_electricboxes = "Limpet (Scuttleport - Platform Next to Electrical Boxes)"
rubberband_scuttleport_magnetdropoff = "Rubber Band (Scuttleport - Ledge Before Second Magnet Dropoff)"
limpet_scuttleport_magnet = "Limpet (Scuttleport - Path to Left After First Magnet)"
anemoneplus_scuttleport_magnetdropoff = "Anemone+ (Scuttleport - Platform Under Second Magnet Dropoff)"
lumpsucker_scuttleport_trashisland = "Lumpsucker (Scuttleport - Trash Island Under Second Magnet Dropoff)"
sinkerplusplus_scuttleport_clam = "Sinker++ (Scuttleport - Clam Next to Stationary Magnet)"
seastar_scuttleport_survivorcamp = "Seastar (Scuttleport - Inside Survivor's Camp Building)"
pufferquill_scuttleport_survivorcamp = "Puffer Quill (Scuttleport - Inside Survivor's Camp Building)"
turtleshell_scuttleport_survivorcamp = "Turtle Shell Shard (Scuttleport - Side Platform After Survivor's Camp Magnet)"
rustynailplus_scuttleport_magrail = "Rusty Nail+ (Scuttleport - Mag-Rail Platform Building Rooftop)"
barnacleplus_scuttleport_propanebridge = "Barnacle+ (Scuttleport - Rooftop Past Propane Tank Bridge)"
salp_scuttleport_propanebridge = "Salp (Scuttleport - Rooftop Past Propane Tank Bridge)"
musselplus_scuttleport_voltai = "Mussel+ (Scuttleport - Outside Voltai Arena)"

barnacle_pinbarge = "Barnacle (Pinbarge)"
musselplus_pinbarge = "Mussel+ (Pinbarge)"

musselplus_unfathom_telephone = "Mussel+ (The Unfathom - Next to Telephone by First Mimic)"
seastarplus_unfathom_glowstick = "Seastar+ (The Unfathom - Past Blue Glowstick)"
lanternfish_unfathom_styrofoam = "Lanternfish (The Unfathom - Styrofoam Box Near Pinbarge Shipwreck)"
lampreyplus_unfathom_pinbargeclam = "Lamprey+ (The Unfathom - Clam Northeast of Pinbarge)"
limpet_unfathom_pinbarge = "Limpet (The Unfathom - Ledge Far Northeast of Pinbarge)"
siphonophoreplus_unfathom_shortcut = "Siphonophore+ (The Unfathom - Ledge North of Second Shortcut)"
salp_unfathom_glowstickfish = "Salp (The Unfathom - Fishing Near Red Glowstick)"
barnacleplus_unfathom_pinbargefish = "Barnacle+ (The Unfathom - Fishing Near Pinbarge Shipwreck)"

sinkerplus_plains_petroch = "Sinker+ (Abyssal Plains - Path East of Petroch)"
pufferquill_plains_inkerton = "Puffer Quill (Abyssal Plains - Southwest of Inkerton Arena)"
rustynailplus_plains_shortcut = "Rusty Nail+ (Abyssal Plains - Next to Shortcut)"
limpetplus_plains_inkerton = "Limpet+ (Abyssal Plains - Southwest of Inkerton Arena)"
whelkplus_plains_shortcut = "Whelk (Abyssal Plains - Southeast of Shortcut)"
zooplanktonplus_plains_shortcut = "Zooplankton+ (Abyssal Plains - East of Shortcut)"
salpplus_plains_entrance = "Salp+ (Abyssal Plains - Above Entrance)"
anothercrab_plains_shortcutclam = "Another Crab (Abyssal Plains - Clam On Ledge East of Shortcut)"
seacucumber_plains_entrance = "Sea Cucumber (Abyssal Plains - North of Entrance)"
fruitsticker_plains_entrance = "Fruit Sticker (Abyssal Plains - North of Entrance)"

sanddollar_oldocean_ledge = "Sand Dollar (The Old Ocean - Ledge North of Second Island)"
barnacleplusplus_oldocean_styrofoam = "Barnacle++ (The Old Ocean - Across Styrofoam Block Hooks)"
seastarplusplus_oldocean_entranceclam = "Seastar++ (The Old Ocean - Clam On Building North of City Entrance)"
spongeplus_oldocean_entrance = "Sponge+ (The Old Ocean - North of City Entrance)"
sanddollar_oldocean_citywall = "Sand Dollar (The Old Ocean - Inside City Walls)"
usedbandageplus_oldocean_citywall = "Used Bandage+ (The Old Ocean - Drop Off Onto City Wall)"
cockleplus_oldocean_snaileast = "Cockle+ (The Old Ocean - In Building East of Snail Shell)"
anothercrab_oldocean_elevator = "Another Crab (The Old Ocean - Under Large Elevator)"
sanddollar_oldocean_easternbuilding = "Sand Dollar (The Old Ocean - Inside Eastern Building)"
phytoplanktonplus_oldocean_clam = "Phytoplankton+ (The Old Ocean - Clam Inside Eastern Building)"
musselplusplus_oldocean_woodplank = "Mussel++ (The Old Ocean - Clam in Secret Area Under Wooden Planks)"
whelkplusplus_oldocean_mantis = "Whelk++ (The Old Ocean - Behind Mantis Punch Wall)"

# costume locations
captain_costume_pickup = "Captain Costume (Central Shallows - Near Nephro Spawn)"
clown_costume_pickup = "Clown Costume (The Sands Between - Path of the Clown)"
sunlight_costume_pickup = "Sunlight Costume (Secluded Ridge - Southern Bonfire)"
intern_costume_pickup = "Intern Costume (Expired Grove Village - Intern Costume)"
cowfishboy_costume_pickup = "CowFishBoy Costume (Flotsam Vale - Butane Tank Island East of Main Entrance)"
bluecollar_costume_pickup = "Blue-Collar Costume (Scuttleport - Cubby in First Room)"
krillionaire_costume_pickup = "Krillionaire Costume (The Unfathom - Next to Nemma)"
exiledflame_costume_pickup = "Exiled Flame Costume (The Unfathom - Path North of Blue Glowstick)"
drkril_costume_pickup = "Dr. Kril Costume (The Old Ocean - Between Pill Bottles)"


# adaptation locations
royal_wave_reward = "Royal Wave Adaptation (Fort Slacktide - Defeat Magista)"
urchin_toss_quest = "Urchin Toss Adaptation (New Carcinia - Hug Erich Too Much)"
bobbit_trap_pickup = "Bobbit Trap (The Sands Between - Top of the Bobbit Den)"

# boss locations
royal_shellsplitter = "Royal Shellsplitter" # first hidden/optional boss of the game in the shallows
nephro = "Nephro, Captain of the Guard" # first boss of the game
platoon_pathfinder = "Polluted Platoon Pathfinder" # miniboss that drops the pristine pearl for the duchess
magista = "Magista, Tyrant of Slacktide" # boss of slacktide, also known as the duchess
pagurus = "Pagurus, The Ravenous" #The big bad of the sands between
lichenthrope = "Diseased Lichenthrope" # the first miniboss of the grove
carbonara_connoisseur = "Curdled Carbonara Connoisseur" # behind the gunk waterfall
heikea = "Heikea, Intimidation Crab" # drops a map piece
topoda = "Grovekeeper Topoda"
consortium = "The Consortium"
sludge_steamroller = "Scuttling Sludge Steamroller"
ceviche_sisters = "Ceviche Sisters"
voltai = "Voltai, The Accumulator"
roland = "Roland, Venture Crabitalist"
petroch = "Petroch, The False Moon"
inkerton = "Inkerton, Crab Hunter"
camtscha = "Camtscha, The Bleached King"
praya_dubia = "Praya Dubia, The Ocean's Agony"
firth = "Firth, The Crab Who Stole The Whorl"

# skill locations
shelleport_skill = "Shelleport Skill (Moon Snail)"
skedaddle_skill = "Skedaddle Skill (Moon Snail)"
parry_skill = "Parry Skill (Moon Snail)"
riposte_skill = "Riposte Skill (Moon Snail)"
natural_defenses_skill = "Natural Defenses (Moon Snail)"
aggravation_skill = "Aggravation Skill (Moon Snail)"
self_repair_skill = "Self-Repair Skill (Moon Snail)"
kintsugi_skill = "Kintsugi Skill (Moon Snail)"
skewer_skill = "Skewer Skill (Moon Snail)"
plunge_skill = "Plunge Skill (Moon Snail)"
scrap_hammer_skill = "Scrap Hammer Skill (Moon Snail)"
dispatch_skill = "Dispatch Skill (Moon Snail)"
spearfishing_skill = "Spearfishing Skill (Moon Snail)"
wave_breaker_skill = "Wave Breaker Skill (Moon Snail)"
streamline_skill = "Streamline Skill (Moon Snail)"
housewarming_skill = "Housewarming Skill (Moon Snail)"
circle_of_life_skill = "Circle of Life Skill (Moon Snail)"
elusive_prey_skill = "Elusive Prey Skill (Moon Snail)"
ebb_and_flow_skill = "Ebb and Flow Skill (Moon Snail)"
umami_training1_skill = "Umami Training 1 Skill (Moon Snail)"
umami_training2_skill = "Umami Training 2 Skill (Moon Snail)"
umami_training3_skill = "Umami Training 3 Skill (Moon Snail)"