# location names to be referenced in Locations.py

# progression/important item locations
fork_pickup = "Fork Pickup" # Kril's main weapon
heartkelp_inital = "Heartkelp Pods Pickup" # the initial heartkelp pods item that the player picks up right at the beginning of the game
fishing_line = "Fishing Line" # grapple ability found in fort slacktide
pristine_pearl = "Pristine Pearl" # reward for defeating platoon pathfinder
map_piece_vale = "Map Piece - Flotsam Vale" # the map piece found in the mailbox in flotsam vale
map_piece_heikea_arena = "Map Piece - Heikea" # the map piece in heikea's boss arena after defeating them
map_piece_pagurus_defeat = "Map Piece - Pagurus" # the map piece obtained after defeating pagurus
home_shell = "Home Shell" # kril's shell, completion location

# currency item locations
breadclaw_caveofrespite_ledge = "Breadclaw (Cave of Respite - Ledge)" # the first breadclaw the player has access to, in the cave of respite
chipclaw_caveofrespite_forkroomfishing = "Chipclaw (Cave of Respite - Fishing Near Fork Pickup)"
mussel_caveofrespite_crabfightfishing = "Mussel (Cave of Respite - Fishing In Crab Fight Tutorial)"
clothesclaw_caveofrespite_entrancefishing = "Clothesclaw (Cave of Respite - Fishing Before Cave Entrance)"
sanddollar_caveofrespite_pathfishing = "Sand Dollar (Cave of Respite - Fishing on Path Before Cave)"

breadclaw_shallows_southsandal = "Breadclaw (Central Shallows - South Red Flip-Flop)"
breadclaw_shallows_westwall = "Breadclaw (Central Shallows - Along West Wall)"
breadclaw_shallows_bridge = "Breadclaw (Central Shallows - Red Flip-Flop Bridge)"
breadclaw_shallows_eastwall = "Breadclaw (Central Shallows - Along East Wall)"
breadclaw_shallows_eastsandal = "Breadclaw (Central Shallows - East Red Flip-Flop)"
breadclaw_shallows_cigarette = "Breadclaw (Central Shallows - Cigarette Butts" # breadclaw on the mound of cigarette butts near nephro's arena
breadclaw_shallows_fortwall = "Breadclaw (Central Shallows - Along Fort Slacktide Wall)"
breadclaw_shallows_wallpiece = "Breadclaw (Central Shallows - East Broken Fort Wall Piece)"
breadclaw_shallows_sandcastle = "Breadclaw (Central Shallows - Southeast Sandcastle)"
breadclaw_shallows_eastledge = "Breadclaw (Central Shallows - East Grapple Ledge)"
hairclaw_shallows_turret = "Hairclaw (Central Shallows - Grapple to Castle Turret)"
chipclaw_shallows_sandcastle = "Chipclaw (Central Shallows - Southwest Sandcastle)"
clothesclaw_shallows_shellsplitter = "Clothesclaw (Central Shallows - Defeat Royal Shellsplitter)"
clothesclaw_shallows_southwestfort = "Clothesclaw (Fort Slacktide - Small Tower Outside Southwest Fort)"
breadclaw_shallows_sunkentower = "Breadclaw (Central Shallows - Sunken Tower near Flip-Flop Bridge)"
breadclaw_shallows_slacktidesouthfish = "Breadclaw (Central Shallows - Fishing South of Slacktide Entrance)"

breadclaw_slacktide_crates = "Breadclaw (Fort Slacktide - Sand Crates and Barrels" # the breadclaw near the line of people waiting to meet the duchess
breadclaw_slacktide_training = "Breadclaw (Fort Slacktide - On South Training Area Wall)"

breadclaw_snailcave_entrance = "Breadclaw (Moon Snail's Cave - Ledge Near Entrance)"
breadclaw_snailcave_shortcut = "Breadclaw (Moon Snail's Cave = Ledge Near Shortcut)"
breadclaw_snailcave_jelly = "Breadclaw (Moon Snail's Cave = Ledge Past Moon Jelly)"

breadclaw_slacktide_crabtrio = "Breadclaw (Fort Slacktide - Near Crab Trio)" # breadclaw found in slacktide post-corruption sitting in a corner near a trio of crabs
chipclaw_slacktide_brokenwall = "Chipclaw (Fort Slacktide - Behind Broken Wall)" # chipclaw found in the room after the enemy breaks out of the wall on the way to fight the duchess
breadclaw_slacktide_roofhiddenfish = "Breadclaw (Fort Slacktide - Path to Roof Hidden Fishing)"

chipclaw_reefsedge_brokenbridge = "Chipclaw (Reef's Edge - Broken Bridge)"
breadclaw_reefsedge_thimblecrab = "Breadclaw (Reef's Edge - Near Thimble Crab)"
hairclaw_reefsedge_sign = "Hairclaw (Reef's Edge - Near I95 Sign On Ledge)"

breadclaw_newcarcinia_entrance = "Breadclaw (New Carcinia - Top of Buildings Near Entrance)"
breadclaw_newcarcinia_hammerhead = "Breadclaw (New Carcinia - Corner Near Hammerhead)"
breadclaw_newcarcinia_bottomalley = "Breadclaw (New Carcinia - Alleyway Near Bottom Feeders)"
breadclaw_newcarcinia_prawnalley = "Breadclaw (New Carcinia - Alleyway Across from Prawn Shop)"
chipclaw_newcarcinia_leg = "Chipclaw (New Carcinia - On Building Near Climbable Mannequin Leg)"
breadclaw_newcarcinia_tallbuilding = "Breadclaw (New Carcinia - On Tall Building Across from Prawn Shop)"
breadclaw_newcarcinia_shortbuilding = "Breadclaw (New Carcinia - On Short Building Across From Mannequin Leg)"
chipclaw_newcarcinia_prawnshop = "Chipclaw (New Carcinia - On Top of Prawn Shop)"

breadclaw_sandsbetween_centralvista = "Breadclaw (The Sands Between - Central Vista Base)"
hairclaw_sandsbetween_southernreef = "Hairclaw (The Sands Between - Above Bobbit Worm near Southern Reef)"
chipclaw_sandsbetween_grove = "Chipclaw (The Sands Between - Sands near Expired Grove Entrance)"
breadclaw_sandsbetween_chains = "Breadclaw (The Sands Between - West Edge near Chains)"
clothesclaw_sandsbetween_bobbit = "Clothesclaw (The Sands Between - Second Terrace in Bobbit Den)"
hairclaw_sandsbetween_bobbit = "Hairclaw (The Sands Between - Third Terrace in Bobbit Den near Bobbit Worm)"
clothesclaw_sandsbetween_northwest = "Clothesclaw (The Sands Between - Rock Northwest of Central Vista)"
clothesclaw_sandsbetween_grove = "Clothesclaw (The Sands Between - Cans near Expired Grove Entrance)"
breadclaw_sandsbetween_propanecliff = "Breadclaw (The Sands Between - Cliff Near Propane)"
hairclaw_sandsbetween_northchains = "Hairclaw (The Sands Between - North of Chains)"
clothesclaw_sandsbetween_litterpitfall = "Clothesclaw (The Sands Between - Pitfall Near Litterbox)"
hairclaw_sandsbetween_southgrovepit = "Hairclaw (The Sands Between - Pitfall South of Grove)"
paperclaw_sandsbetween_southeelshortcut = "Paperclaw (The Sands Between - Southern Eelectrocute Path, Near Shortcut)"
hairclaw_sandsbetween_southeel = "Hairclaw (The Sands Between - South Eelectrocute Path Second Jump)"
paperclaw_sandsbetween_trashanchor = "Paperclaw (The Sands Between - Behind Trashbag Near Anchor)"
hairclaw_sandsbetween_anchorfish = "Hairclaw (The Sands Between - Fishing Near Anchor)"
chipclaw_sandsbetween_northeastchainfish = "Chipclaw (The Sands Between - Fishing North East of Chains)"
clothesclaw_sandsbetween_propanefish = "Clothesclaw (The Sands Between - Fishing Near Propane Tank)"
clothesclaw_sandsbetween_anchorcentralfish = "Clothesclaw (The Sands Between - Fishing Between Central Vista and Anchor)"
breadclaw_sandsbetween_nailfish = "Breadclaw (The Sands Between - Fishing Near Nail)"
breadclaw_sandsbetween_palletfish = "Breadclaw (The Sands Between - Fishing In Wooden Pallet)"
hairclaw_sandsbetween_southeelfish = "Hairclaw (The Sands Between - South Eelectrocute Path Large Island Fishing)"
chipclaw_sandsbetween_anchoreelhiddenfish = "Chipclaw (The Sands Between - Hidden Fishing on Stone Cliff Near Anchor)"

stapleclaw_postpag_litter = "Stapleclaw (Post Pagurus - Litterbox)"
hairclaw_postpag_chains = "Hairclaw (Post Pagurus - Middle of Chains)"
clothesclaw_postpag_chains = "Clothesclaw (Post Pagurus - Middle of Chains)"
hairclaw_postpag_nridge = "Hairclaw (Post Pagurus - North of Ridge Overlook)"
hairclaw_postpag_ecentral = "Hairclaw (Post Pagurus - East of Central Vista)"
chipclaw_postpag_nwpropane = "Chipclaw (Post Pagurus - Preserver North-West of Propane)"
paperclaw_postpag_schain = "Paperclaw (Post Pagurus - South of Chains)"

clothesclaw_ridge_neridge = "Clothesclaw (Secluded Ridge - North East Secluded Ridge)"
paperclaw_ridge_nearoverlook = "Paperclaw (Secluded Ridge - Hidden Crab near Ridge Overlook)"
clothesclaw_ridge_broom = "Clothesclaw (Secluded Ridge - Near Broom)"
breadclaw_ridge_south = "Breadclaw (Secluded Ridge - Southern Path)"
clothesclaw_ridge_overlookfish = "Clothesclaw (Secluded Ridge - Fishing on Ridge Overlook)"
chipclaw_ridge_southfish = "Chipclaw [Currency] (Fishing South of Ridge Overlook)"

stapleclaw_trashbin_eelfish = "Stapleclaw (Trashbin Plateau - Eelectrocute Grapple Path Fishing)"

breadclaw_grovemain_takeout = "Breadclaw (Expired Grove Main - East Takeout Container)"
breadclaw_grovemain_tiretop = "Breadclaw (Expired Grove Main - Near Tire Archway)"
chipclaw_grovemain_plastic = "Chipclaw (Expired Grove Main - Plastic Silverware Near Entrance)"
clothesclaw_grovemain_choccymilk = "Clothesclaw (Expired Grove Main - Chocolate Milk Carton)"
breadclaw_grovemain_insidetire = "Breadclaw (Expired Grove Main - Inside Tire Archway)"
chipclaw_grovemain_sniper = "Chipclaw (Expired Grove Main - East Sniper Ledge)"
hairclaw_grovemain_milkurchins = "Hairclaw (Expired Grove Main - Milk Carton Urchins)"
breadclaw_grovemain_smallhall = "Breadclaw (Expired Grove Main - Small Connecting Hallway)"
chipclaw_grovemain_apples = "Chipclaw (Expired Grove Main - Rotten Apple Cores)"
chipclaw_grovemain_sodacans = "Chipclaw (Expired Grove Main - Shopping Cart Soda Cans)"
hairclaw_grovemain_moonshine = "Hairclaw (Expired Grove Main - Shopping Cart Moonshine)"
chipclaw_grovemain_circlerock = "Chipclaw (Expired Grove Main - Circular Rock Past Shopping Cart)"
clothesclaw_grovemain_alcove = "Clothesclaw (Expired Grove Main - Gunk River Alcove Near Waterfall)"
hairclaw_grovemain_sniper = "Hairclaw (Expired Grove Main - Elevated Sniper Platform)"
breadclaw_grovemain_amongus = "Breadclaw (Expired Grove Main - Among Us Fries)"
breadclaw_grovemain_oildrum = "Breadclaw (Expired Grove Main - Small Platform Next to Oil Drum)"
breadclaw_grovemain_oilgrapple = "Breadclaw (Expired Grove Main - Grapple Near Top of Oil Drum)"
clothesclaw_grovemain_mantisfish = "Clothesclaw (Expired Grove Main - Fishing Near Mantis Block)"
hairclaw_grovemain_fishing = "Hairclaw (Expired Grove Main - Hidden Fishing Near Milk Carton)"
clothesclaw_grovemain_riverfish = "Clothesclaw (Expired Grove Main - River Fishing Near Carbonara Waterfall)"

breadclaw_grovevillage_oildrum = "Breadclaw (Expired Grove Village - After Oil Drum)"
breadclaw_grovevillage_bottle1 = "Breadclaw (Expired Grove Village - In Bottle Near Cart Mantis Block 1)"
breadclaw_grovevillage_bottle2 = "Breadclaw (Expired Grove Village - In Bottle Near Cart Mantis Block 2)"
chipclaw_grovevillage_netorbs = "Chipclaw (Expired Grove Village - Near Net Orbs After Heikea)"
hairclaw_grovevillage_river = "Hairclaw (Expired Grove Village - River Fishing Before Oil Drum)"
chipclaw_grovevillage_NWcarton = "Chipclaw (Expired Grove Village - In North West Milk Carton)"
chipclaw_grovevillage_SEcarton = "Chipclaw (Expired Grove Village - In South East Milk Carton)"
chipclaw_grovevillage_NEcarton = "Chipclaw (Expired Grove Village - In North East Milk Carton)"
breadclaw_grovevillage_shortcut = "Breadclaw (Expired Grove Village - Near Cave Shortcut)"
chipclaw_grovevillage_cave = "Chipclaw (Expired Grove Village - Near End of Cave)"
hairclaw_grovevillage_entrance = "Hairclaw (Expired Grove Village - Near Village Entrance)"
breadclaw_grovevillage_Scarton = "Breadclaw (Expired Grove Village - In South Milk Carton)"
breadclaw_grovevillage_entrance = "Breadclaw (Expired Grove Village - Behind bottles at Village Entrance)"
hairclaw_grovevillage_NEcarton = "Hairclaw (Expired Grove Village - In North East High Milk Carton)"
clothesclaw_grovevillage_upsidedown = "Clotheclaw (Expired Grove Village - Upside Down Village)"
clothesclaw_grovevillage_dock = "Clothesclaw (Expired Grove Village - Dock Fishing Spot 3)"
hairclaw_grovevillage_dock = "Hairclaw (Expired Grove Village - Dock Fishing Spot 4)"
clothesclaw_grovevillage_hidden = "Clothesclaw (Expired Grove Village - Hidden Fishing on Topoda Path)"
carclaw_grovevillage_topoda = "Carclaw (Expired Grove Village - In Topoda Arena)"

chipclaw_flotsamvale_sheetmetal = "Chipclaw (Flotsam Vale - Sheet Metal Near Main Entrance)"
chipclaw_flotsamvale_beach = "Chipclaw (Flotsam Vale - Beach North of Main Entrance)"
breadclaw_flotsamvale_northgunk = "Breadclaw (Flotsam Vale - Gunk North of main Entrance)"
chipclaw_flotsamvale_butaneisland = "Chipclaw (Flotsam Vale - Butane Tank Island East of Main Entrance)"
clothesclaw_flotsamvale_butaneisland = "Clothesclaw (Flotsam Vale - Butane Tank Island East of Main Entrance)"
clothesclaw_flotsamvale_alcove = "Clothesclaw (Flotsam Vale - Small Alcove Northeast of Main Entrance)"
chipclaw_flotsamvale_cavepath = "Chipclaw (Flotsam Vale - Cave Path to Upper Flotsam Vale)"
clothesclaw_flotsamvale_cavepath = "Clothesclaw (Flotsam Vale - Cave Path to Upper Flotsam Vale)"
paperclaw_flotsamvale_uppersnail = "Paperclaw (Flotsam Vale - Upper Flotsam Vale Near Snail Shell)"
breadclaw_flotsamvale_woodplatform = "Breadclaw (Flotsam Vale - Wooden Platform Above Sludge Steamroller)"
clothesclaw_flotsamvale_woodplatform = "Clothesclaw (Flotsam Vale - Wooden Platform Above Sludge Steamroller)"
hairclaw_flotsamvale_woodplatform = "Hairclaw (Flotsam Vale - Wooden Platform Above Sludge Steamroller)"
clothesclaw_flotsamvale_trashpile = "Clothesclaw (Flotsam Vale - Trash Pile Near Sludge Steamroller)"
paperclaw_flotsamvale_southbutane = "Paperclaw (Flotsam Vale - Butane Tank South of Sludge Steamroller)"
chipclaw_flotsamvale_westbutane = "Chipclaw (Flotsam Vale - Butane Tanks West of Sludge Steamroller)"
breadclaw_flotsamvale_crane = "Breadclaw (Flotsam Vale - Next to Crane Switch)"
hairclaw_flotsamvale_mailboxbutane = "Hairclaw (Flotsam Vale - Butane Tanks Southwest of Mailbox)"
paperclaw_flotsamvale_mailboxplatform = "Paperclaw (Flotsam Vale - Elevated Platform Southwest of Mailbox)"
chipclaw_flotsamvale_APunder1 = "Chipclaw (Flotsam Vale - Air Pocket Cave Underwater 1)"
hairclaw_flotsamvale_APabove1 = "Hairclaw (Flotsam Vale - Air Pocket Cave Above Water 1)"
hairclaw_flotsamvale_APunder1 = "Hairclaw (Flotsam Vale - Air Pocket Cave Underwater 1)"
hairclaw_flotsamvale_APunder2 = "Hairclaw (Flotsam Vale - Air Pocket Cave Underwater 2)"
chipclaw_flotsamvale_APunder2 = "Chipclaw (Flotsam Vale - Air Pocket Cave Underwater 2)"
clothesclaw_flotsamvale_APabove = "Clothesclaw (Flotsam Vale - Air Pocket Cave Above Water)"
hairclaw_flotsamvale_APabove2 = "Hairclaw (Flotsam Vale - Air Pocket Cave Above Water 2)"
paperclaw_flotsamvale_shippingdock = "Paperclaw (Flotsam Vale - Under Shipping Port Dock)"
hairclaw_flotsamvale_trashpile = "Hairclaw (Flotsam Vale - Trash Pile Past Shipping Dock)"
clothesclaw_flotsamvale_consortium = "Clothesclaw (Flotsam Vale - Top of Cage Before Consortium)"
paperclaw_flotsamvale_billboard = "Paperclaw (Flotsam Vale - Behind License Plate Billboard by Scuttleport)"
chipclaw_flotsamvale_consortiumgrapple = "Chipclaw (Flotsam Vale - Past Consortium)"
clothesclaw_flotsamvale_northfish = "Clothesclaw (Flotsam Vale - North Gunk Lake Fishing)"
breadclaw_flotsamvale_westfish = "Breadclaw (Flotsam Vale - West Gunk Lake Fishing Near Shore)"
clothesclaw_flotsamvale_northshorefish = "Clothesclaw (Flotsam Vale - North Gunk Lake Fihsing Near Shore)"
clothesclaw_flotsamvale_southfish = "Clothesclaw (Flotsam Vale - Gunk Lake Fishing South of Sludge Steamroller)"
hairclaw_flotsamvale_APfish = "Hairclaw (Flotsam Vale - Gunk Lake Fishing Outside Air Pocket Cave)"
chipclaw_flotsamvale_consortiumfish = "Chipclaw (Flotsam Vale - Fishing Past Consortium)"
paperclaw_flotsamvale_uppervale = "Paperclaw (Flotsam Vale - Near Upper Flotsam Vale)"
breadclaw_flotsamvale_gunkfish = "Breadclaw (Flotsam Vale - Gunk Fishing on Docks)"
clothesclaw_flotsamvale_gunkfish = "Clothesclaw (Flotsam Vale - Gunk Fishing on Docks)"
hairclaw_flotsamvale_gunkfish = "Hairclaw (Flotsam Vale - Gunk Fishing Near Bridge)"
chipclaw_flotsamvale_gunkfish = "Chipclaw (Flotsam Vale - Gunk Fishing Under Middle Tower)"


breadclaw_scuttleport_cubby = "Breadclaw (Scuttleport - Cubby in First Room)"
clothesclaw_scuttleport_cubby = "Clothesclaw (Scuttleport - Cubby in First Room)"
hairclaw_scuttleport_cubbies = "Hairclaw (Scuttleport - Between Cubbies in First Room)"
breadclaw_scuttleport_grate = "Breadclaw (Scuttleport - On Grate Left of Firt Room)"
hairclaw_scuttleport_magnet = "Hairclaw (Scuttleport - After First Magnet)"
clothesclaw_scuttleport_electriccrab = "Clothesclaw (Scuttleport - Next to Electric Long-Legged Crab)"
clothesclaw_scuttleport_trashisland = "Clothesclaw (Scuttleport - Trash Island Under Second Magnet Dropoff)"
paperclaw_scuttleport_elevator = "Paperclaw (Scuttleport - Elevator Under Second Magnet Dropoff)"
hairclaw_scuttleport_rooftopedge = "Hairclaw (Scuttleport - Near Edge of First Rooftop)"
hairclaw_scuttleport_rooftoptrash = "Hairclaw (Scuttleport - Between Trasw Blocks on First Rooftop)"
hairclaw_scuttleport_survivorcamp = "Hairclaw (Scuttleport - Edge of Survivor's Camp Rooftop)"
clothesclaw_scuttleport_npccrab = "Clothesclaw (Scuttleport - On Balcony Next to NPC Crab)"
chipclaw_scuttleport_survivorcamp = "Chipclaw (Scuttleport - Inside Survivor's Camp Building)"
clothesclaw_scuttleport_magrail1 = "Clothesclaw (Scuttleport - Mag-Rail Platform Building 1)"
clothesclaw_scuttleport_magrail2 = "Clothesclaw (Scuttleport - Mag-Rail Platform Building 2)"
hairclaw_scuttleport_magrailroof1 = "Hairclaw (Scuttleport - Mag-Rail Platform Building Rooftop 1)"
paperclaw_scuttleport_magrail = "Paperclaw (Scuttleport - Trashblocks on Mag-Rail Building Platform Builing Rooftop)"
hairclaw_scuttleport_magrailroof2 = "Hairclaw (Scuttleport - Mag-Rail Platform Building Rooftop 2)"
chipclaw_scuttleport_magrail = "Chipclaw (Scuttleport - Mag-Rail Platform Building Rooftop)"
hairclaw_scuttleport_magrail = "Hairclaw (Scuttleport - Mag-Rail Platform Building)"
chipclaw_scuttleport_propanebridge = "Chipclaw (Scuttleport - Inside Propane Tank Bridge)"
clothesclaw_scuttleport_propanebridge = "Clothesclaw (Scuttleport - Inside Propane Tank Bridge)"

paperclaw_pinbarge = "Paperclaw (Pinbarge)"
stapleclaw_pinbarge = "Stapleclaw (Pinbarge)"

stapleclaw_unfathom_eastclam = "Stapleclaw (The Unfathom - Clam on Path to The East)"
paperclaw_unfathom_vcr = "Paperclaw (The Unfathom - Under the VCR)"
paperclaw_unfathom_glowstickclam = "Paperclaw (The Unfathom - Clam Past Red Glowstick)"
clothesclaw_unfathom_cassette = "Clothesclaw (The Unfathom - Cassette Tape Near Nemma Shortcut)"
clothesclaw_unfathom_pinbarge1 = "Clothesclaw (The Unfathom - Nearby Pinbarge Shipwreck 1)"
clothesclaw_unfathom_pinbarge2 = "Clothesclaw (The Unfathom - Nearby Pinbarge Shipwreck 2)"
paperclaw_unfathom_pinbarge = "Paperclaw (The Unfathom - Nearby Pinbarge Shipwreck)"
paperclaw_unfathom_shortcut = "Paperclaw (The Unfathom - Next to Second Shortcut)"
paperclaw_unfathom_glowstick = "Paperclaw (The Unfathom - Next to Glowstick Northeast of Pinbarge)"
paperclaw_unfathom_northeastbarge = "Paperclaw (The Unfathom - Ledge Far Northeast of Pinbarge)"
clothesclaw_unfathom_shortcut = "Clothesclaw (The Unfathom - Ledge North of Second Shortcut)"
chipclaw_unfathom_shortcuthill = "Chipclaw (The Unfathom - Hill North of Second Shortcut)"
hairclaw_unfathom_shortcut = "Hairclaw (The Unfathom - North of Second Shortcut)"
hairclaw_unfathom_styrofoam = "Hairclaw (The Unfathom - Styrofoam North of Second Shortcut)"

clothesclaw_plains_entrance = "Clothesclaw (Abyssal Plains - Near Entrance)"
hairclaw_plains_entrance = "Hairclaw (Abyssal Plains - North of Entrance)"
hairclaw_plains_shortcut = "Hairclaw (Abyssal Plains - Near Shortcut)"
stapleclaw_plains_fish = "Stapleclaw (Abyssal Plains - Fishing Southeast of Shortcut)"

paperclaw_oldocean_northhouse = "Paperclaw (The Old Ocean - Styrofoam House North of Snail Shell)"
hairclaw_oldocean_northhouse = "Hairclaw (The Old Ocean - Styrofoam House North of Snail Shell)"
paperclaw_oldocean_mainshortcut = "Paperclaw (The Old Ocean - Near Shortcut Along Main Path)"
paperclaw_oldocean_islandhouse = "Paperclaw (The Old Ocean - Styrofoam House on Second Island)"
clothesclaw_oldocean_bubbles = "Clothesclaw (The Old Ocean - Area Below First Bubble Jumps)"
paperclaw_oldocean_shortcut = "Paperclaw (The Old Ocean - Near Large Shortcut)"
hairclaw_oldocean_shortcut = "Hairclaw (The Old Ocean - Near Large Shortcut)"
paperclaw_oldocean_southhouse = "Paperclaw (The Old Ocean - Styrofoam House South of Second Island)"
carclaw_oldocean_islandclam = "Carclaw (The Old Ocean - Clam Middle of Second Island)"
stapleclaw_oldocean_brokenbridge = "Stapleclaw (The Old Ocean - On Broken Bridge to City)"
paperclaw_oldocean_scourcrab = "Paperclaw (The Old Ocean - On Ledge by Scour Crab)"
hairclaw_oldocean_northentrance = "Hairclaw (The Old Ocean - North of City Entrance)"
hairclaw_oldocean_cityentrance = "Hairclaw (The Old Ocean - Near City Entrance)"
paperclaw_oldocean_northentrance = "Paperclaw (The Old Ocean - North of City Entrance)"
hairclaw_oldocean_citygates = "Hairclaw (The Old Ocean - Platform Past City Gates Snail Shell)"
paperclaw_oldocean_citygates = "Paperclaw (The Old Ocean - Platform Past City Gates Snail Shell)"
clothesclaw_oldocean_citygates = "Clothesclaw (The Old Ocean - Southeast of City Gates Snail Shell)"
clothesclaw_oldocean_seafoam = "Clothesclaw (The Old Ocean - Ledge Near Seafoam Cans)"
carclaw_oldocean_seafoam = "Carclaw (The Old Ocean - Clam Near Seafoam Cans)"
hairclaw_oldocean_brokenshell = "Hairclaw (The Old Ocean - On Ledge Inside Broken Shell)"
breadclaw_oldocean_teethtrap = "Breadclaw (The Old Ocean - Inside Teeth Trap in Hallway)"
hairclaw_oldocean_woodplank = "Hairclaw (The Old Ocean - Drop Down to Wooden Planks)"
carclaw_oldocean_scourcrab = "Carclaw (The Old Ocean - Top of Building Behind Scour Crab)"
paperclaw_oldocean_eastsnail = "Paperclaw (The Old Ocean - East of Snail Shell)"
hairclaw_oldocean_scourcrab = "Hairclaw (The Old Ocean - Floating Platform Next to Scour Crab)"
paperclaw_oldocean_scourledge = "Paperclaw (The Old Ocean - Small Ledge Near Scour Crab)"
stapleclaw_oldocean_parkour = "Stapleclaw (The Old Ocean - Staircase Up to Long Parkour)"
stapleclaw_oldocean_middlebuilding = "Stapleclaw (The Old Ocean - Drop Down in Middle Building)"
carclaw_oldocean_eastbuilding = "Carclaw (The Old Ocean - Outside Eastern Building)"
carclaw_oldocean_camtscha = "Carclaw (The Old Ocean - Outside Camtscha's Arena)"
stapleclaw_oldocean_eastbuilding = "Stapleclaw (The Old Ocean - Ledge Outside Eastern Building)"
carclaw_oldocean_camtschapath = "Carclaw (The Old Ocean - Pathway to Camtscha's Arena)"
stapleclaw_oldocean_camtschastairs = "Stapleclaw (The Old Ocean - Large Staircase in Front of Camtscha Arena)"
carclaw_oldocean_middlebuilding = "Carclaw (The Old Ocean - Clam in Middle Building)"

# upgrade item locations
bloodstar_shallows_help = "Bloodstar Limb (Central Shallows - Help a Crab)" # the bloodstar limb acquired from helping the surrounded crab in the shallows
bloodstar_shallows_parkour = "Bloodstar Limb (Central Shallows - Parkour on Small Islands)"
bloodstar_shallows_bridge = "Bloodstar Limb (Central Shallows - Ledge Near Red Flip-Flop Bridge)"
bloodstar_shallows_clam = "Bloodstar Limb (Central Shallow - Southwest Sandcastle Clam)"

kelpsprout_snailcave_elevator = "Heartkelp Sprout (Moon Snail's Cave - Moon Jelly Elevators)"
bloodstar_snailcave_platoon = "Bloodstar Limb (Moon Snail's Cave - Just Before Platoon Pathfinder)"

bloodstar_slacktide_clam = "Bloodstar Limb (Slacktide - Clam Above Duchess's Chamber)" # bloodstar limb found by grappling up in the area before you fight the duchess and opening the clam

stainlessrelic_reefsedge_coral = "Stainless Relic (Reef's Edge - Flat Coral Near Entrance)"

bloodstar_sandsbetween_playground = "Bloodstar Limb (The Sands Between - Cup House in Playground Town near Flotsam)"
tacklepouch_sandsbetween_cooler = "Tackle Pouch (The Sands Between - Cooler on Southern Edge)"
bloodstar_sandsbetween_southwestcentral = "Bloodstar Limb (The Sands Between - Rocks Southwest of Central Vista)"
oldworldwhorl_sandsbetween_mantispitfall = "Old World Whorl (The Sands Between - Mantis Block Pitfall North of Central Vista)"
stainlessrelic_sandsbetween_eelectrocute = "Stainless Relic (The Sands Between - On Electric Crab Platform)"
tacklepouch_sandsbetween_eelnorthchain = "Tackle Pouch (The Sands Between - Eelectrocute Crab North of Chains)"
kelpsprout_sandsbetween_southeelside = "Hearkelp Sprout (The Sands Between - South Eelectrocute Path, Green Coral Side Path)"

bloodstar_postpag_anchorswarm = "Bloodstar Limb (Post Pagurus - Crab Swarm Near Anchor)"

stainlessrelic_ridge_overlook = "Stainless Relic (Secluded Ridge - Plate on Ridge Overlook)"
kelpsprout_ridge_eelend = "Heartkelp Sprout (Secluded Ridge - End of Eelectrocute Path, Near Bobbit)"
oldworldwhorl_ridge_ncliff = "Old World Whorl (Secluded Ridge - North Cliff Clam)"
oldworldwhorl_ridge_eelclam = "Old World Whorl (Secluded Ridge - Eelectrocute Clam)"

oldworldwhorl_grovemain_southclam = "Old World Whorl (Expired Grove Main - South Clam)"
bloodstar_grovemain_waterfall = "Bloodstar Limb (Expired Grove Main - Behind Gunk Waterfall)"
kelpsprout_grovemain_carts = "Heartkelp Sprout (Expired Grove Main - Top of Shopping Cart Buildings)"

bloodstar_grovevillage_carton = "Bloodstar Limb (Expired Grove Village - In Upper South Milk Carton)"
tacklepouch_grovevillage_clam = "Tackle Pouch (Expired Grove Village - Clam Near Cave Shortcut)"
stainlessrelic_grovevillage_clam = "Stainless Relic (Expired Grove Village - Clam in Hammer Crab Cave)"
oldworldwhorl_grovevillage_topoda = "Old World Whorl (Expired Grove Village - Post-Topoda Mantis Block)"

bloodstar_flotsamvale_submerged = "Bloodstar Limb (Flotsam Vale - North Submerged Butane Tank)"
oldworldwhorl_flotsamvale_cavepath = "Old World Whorl (Flotsam Vale - Cave Path to Upper Flotsam Vale Clam)"
oldworldwhorl_flotsamvale_snail = "Old World Whorl (Flotsam Vale - Upper Flotsam Vale Past Snail Shell)"
bloodstar_flotsamvale_craneclam = "Bloodstar Limb (Flotsam Vale - Clam on Crane Platform Near Mailbox)"
tacklepouch_flotsamvale_waterfall = "Tacklepouch (Flotsam Vale - Behind Waterfall)"

stainlessrelic_scuttleport_clam = "Stainless Relic (Scuttleport - Clam on Left Path After First Magnet)"
bloodstar_scuttleport_magrailclam = "Bloodstar Limb (Scuttleport - Clam on Mag-Rail Platform Building Rooftop)"
stainlessrelic_scuttleport_magrail = "Stainless Relic (Scuttleport - Mag-Rail Platform Building)"
stainlessrelic_scuttleport_propanebridge = "Stainless Relic (Scuttleport - Building Past Propane Tank Bridge)"
oldworldwhorl_scuttleport_eelectrocute = "Old World Whorl (Scuttleport - Eelectrocute Room in Survivor's Camp Building)"

bloodstar_unfathom_eastpath = "Bloodstar Limb (The Unfathom - Path to The East)"
bloodstar_unfathom_shortcut = "Bloodstar Limb (The Unfathom - Past Second Shortcut)"

stainlessrelic_plains_sponges = "Stainless Relic (Abyssal Plains - Across Bouncy Sponges East of Petroch)"
stainlessrelic_plains_snipers = "Stainless Relic (Abyssal Plains - Between Giant Sniper Crabs)"
oldworldwhorl_plains_shortcut = "Old World Whorl (Abyssal Plains - Southeast of Shortcut)"
bloodstar_plains_shortcutclam = "Bloodstar Limb (Abyssal Plains - Clam in Cave East of Shortcut)"
kelpsprout_plains_grappleclam = "Hearkelp Sprout (Abyssal Plains - Clam East of Petroch)"
tacklepouch_plains_grapplesnail = "Tackle Pouch (Abyssal Plains - Across Grapple Hooks by Snail Shell)"

oldworldwhorl_oldocean_ledgeclam = "Old World Whorl (The Old Ocean - Clam on Ledge North of Snail Shell)"
bloodstar_oldocean_brokenbridge = "Bloodstar Limb (The Old Ocean - Under Broken Bridge to City)"
bloodstar_oldocean_citygates = "Bloodstar Limb (The Old Ocean - Drop Down Southeast of City Gates Snail Shell)"
stainlessrelic_oldocean_citywall = "Stainless Relic (The Old Ocean - Inside City Walls)"
kelpsprout_oldocean_parkourclam = "Hearkelp Sprout (The Old Ocean - Clam Past Seafoam Parkour)"
stainlessrelic_oldocean_styrofoamclam = "Stainless Relic (The Old Ocean - Clam on Top of Styrofoam Building)"
bloodstar_oldocean_easternbuilding = "Bloodstar Limb (The Old Ocean - Inside Eastern Building)"
oldworldwhorl_oldocean_easternclam = "Old World Whorl (The Old Ocean - Clam in Eastern Building)"

# consumable item locations
barbedhook_reefsedge_undercoral = "Barbed Hook (Reef's Edge - Under Coral Near Shot Glass Crab)"
barbedhook_reefsedge_seahorses = "Barbed Hook (Reef's Edge - Coral Near Two Seahorses)"
barbedhook_reefsedge_shortcut = "Barbed Hook (Reef's Edge - Near Shortcut)"
barbedhook_reefsedge_cliff = "Barbed Hook (Reef's Edge - North Facing Cliff Near Seahorse)"

barbedhook_newcarcinia_citycenter = "Barbed Hook (New Carcinia - Top of Building in City Center)"

barbedhook_sandsbetween_centralvista = "Barbed Hook (The Sands Between - Central Vista Near Safety Tube)"
barbedhook_sandsbetween_southernreef = "Barbed Hook (The Sands Between - Pizza Box near Southern Reef)"
barbedhook3_sandsbetween_cooler = "Barbed Hook x3 (The Sands Between - North of Cooler)"
barbedhook_sandsbetween_fence = "Barbed Hook (The Sands Between - Fence Southwest of Cooler)"
barbedhook_sandsbetween_spire = "Barbed Hook (The Sands Between - Top of Spire Near Grove Entrance)"
barbedhook_sandsbetween_southcentral = "Barbed Hook (The Sands Between - South of Central Vista, Near Fence)"
barbedhook_sandsbetween_bobbitbase = "Barbed Hook (The Sands Between - Base of Bobbit Hill)"
barbedhook_sandsbetween_northofridge = "Barbed Hook (The Sands Between - North of Secluded Ridge)"
barbedhook_sandsbetween_southeel = "Barbed Hook (The Sands Between - South Eelectrocute Path Large Island)"
barbedhook_sandsbetween_southeelshellsplitter = "Barbed Hook (The Sands Between - South Eelectrocute Path Near Shellsplitter)"

barbedhook_postpag_nechain = "Barbed Hook (Post Pagurus - Near Northeastern Chain)"
barbedhook_postpag_echain = "Barbed Hook (Post Pagurus - East of Chains)"
barbedhook_postpag_echainpreserver = "Barbed Hook (Post Pagurus - Near Preserver East of Chains)"
barbedhook_postpag_necentral = "Barbed Hook (Post Pagurus - Rocks North-East of Central Vista)"
barbedhook_postpag_nwridge = "Barbed Hook (Post Pagurus - Rocks North-West of Ridge Overlook)"
barbedhook_postpag_neeelpath = "Barbed Hook (Post Pagurus - Fence Near North-East Eelectrocute Path)"
barbedhook_postpag_ridgeentrance = "Barbed Hook (Post Pagurus - Near Secluded Ridge Entrance)"
barbedhook_postpag_wplayground = "Barbed Hook (Post Pagurus - West of Playground)"
barbedhook_postpag_swcentral = "Barbed Hook (Post Pagurus - South-West of Central Vista)"

barbedhook_ridge_near = "Barbed Hook (Secluded Ridge - Near Secluded Ridge Moon Snail Shell)"
barbedhook_ridge_overlookpath = "Barbed Hook (Secluded Ridge - Path to Ridge Overlook)"
sharkegg_ridge_broomspire = "Shark Egg (Secluded Ridge - Broom Spire Peak)"

barbedhook_trashbin_eelgrapple = "Barbed Hook (Trashbin Plateau - Eelectrocute Grapple Path)"

barbedhook_grovemain_sniper = "Barbed Hook (Expired Grove Main - Next to Sniper Crab)"
barbedhook_grovemain_riverledge = "Barbed Hook (Expired Grove Main - Ledge Near Gunk River)"
barbedhook_grovemain_riversand = "Barbed Hook (Expired Grove Main - In Sand Near Gunk River)"
barbedhook_grovemain_lichenthrope = "Barbed Hook (Expired Grove Main - Behind Diseased Lichenthrope)"
barbedhook_grovemain_lichenthropeeast = "Barbed Hook (Expired Grove Main - Ledge East of Lichenthrope)"
barbedhook_grovemain_sodacans = "Barbed Hook (Expired Grove Main - Crushed Soda Cans)"
barbedhook_grovemain_acrossriver = "Barbed Hook (Expired Grove Main - Ledge Across Gunk River)"
barbedhook_grovemain_afternets = "Barbed Hook (Expired Grove Main - Ledge After Grapple Nets)"
barbedhook_grovemain_cartledge = "Barbed Hook (Expired Grove Main - Ledge After Shopping Cart)"
barbedhook_grovemain_cartledgebottle = "Barbed Hook (Expired Grove Main - Bottles on Ledge After Shopping Cart)"
barbedhook_grovemain_paperplate = "Barbed Hook (Expired Grove Main - Paper Plate Near River)"
barbedhook_grovemain_oildrum = "Barbed Hook (Expired Grove Main - Main Pathway Around Oil Drum)"
barbedhook_grovemain_canopy = "Barbed Hook  (Expired Grove Main - Carton Canopy)"
barbedhook_grovemain_drumtop = "Barbed Hook (Expired Grove Main - Near Top of Oil Drum)"
barbedhook_grovemain_carts = "Barbed Hook (Expired Grove Main - Shopping Cart Buildings)"
sharkegg_grovemain_mantis = "Shark Egg (Expired Grove Main - Mantis Block on Left Path)"

barbedhook_grovevillage_heikea = "Barbed Hook (Expired Grove Village - In Cave After Heikea)"
barbedhook_grovevillage_cartfish = "Barbed Hook (Expired Grove Village - Hidden Fishing Near Shopping Cart Mantis Block)"
barbedhook_grovevillage_riveroil = "Barbed Hook (Expired Grove Village - River Fishing After Oil Drum)"
barbedhook_grovevillage_bottles = "Barbed Hook (Expired Grove Village - Bottles Before Heikea)"
barbedhook_grovevillage_crabs = "Barbed Hook (Expired Grove Village - Between Two Crabs)"
barbedhook_grovevillage_centercarton = "Barbed Hook (Expired Grove Village - In Center Milk Carton)"
barbedhook_grovevillage_corpse = "Barbed Hook (Expired Grove Village - In Center Near Corpse)"
barbedhook_grovevillage_path = "Barbed Hook (Expired Grove Village - On Center Path)"
barbedhook_grovevillage_Ncarton = "Barbed Hook (Expired Grove Village - In North Milk Carton)"
barbedhook_grovevillage_SWcarton = "Barbed Hook (Expired Grove Village - In South West Milk Carton)"
sharkegg_grovevillage_sniper = "Shark Egg (Expired Grove Village - Near Village Sniper)"
barbedhook_grovevillage_boat = "Barbed Hook (Expired Grove Village - Under Heikea Boat)"
barbedhook_grovevillage_butter = "Barbed Hook (Expired Grove Village - Butter Carton in Cave)"
barbedhook_grovevillage_above1 = "Barbed Hook (Expired Grove Village - Above Village 1)"
barbedhook_grovevillage_above2 = "Barbed Hook (Expired Grove Village - Above Village 2)"
barbedhook_grovevillage_above3 = "Barbed Hook (Expired Grove Village - Above Village 3)"
barbedhook_grovevillage_ornament = "Barbed Hook (Expired Grove Village - In Bottle After Ornament Parkour)"
barbedhook_grovevillage_hammer = "Barbed Hook (Expired Grove Village - In Hammer Crab Cave)"
barbedhook_grovevillage_dock = "Barbed Hook (Expired Grove Village - Dock Fishing Spot 1)"

barbedhook_flotsamvale_entranceledge = "Barbed Hook (Flotsam Vale - Ledge Near Main Entrance)"
barbedhook_flotsamvale_entrancerocks = "Barbed Hook (Flotsam Vale - Rocks Near Main Entrance)"
barbedhook_flotsamvale_northbeach = "Barbed Hook (Flotsam Vale - Beach North of Main Entrance)"
barbedhook_flotsamvale_butaneisland = "Barbed Hook (Flotsam Vale - Butane Tank Island East of Main Entrance)"
barbedhook_flotsamvale_snailshell = "Barbed Hook (Flotsam Vale - Upper Flotsam Vale Near Snail Shell)"
barbedhook_flotsamvale_wooddeck = "Barbed Hook (Flotsam Vale - Wooden Deck Above Propane Tank)"
barbedhook_flotsamvale_woodplatform1 = "Barbed Hook (Flotsam Vale - Wooden Platform Above Sludge Steamroller 1)"
barbedhook_flotsamvale_woodplatform2 = "Barbed Hook (Flotsam Vale - Wooden Platform Above Sludge Steamroller 2)"
barbedhook_flotsamvale_westbutane = "Barbed Hook (Flotsam Vale - Butane Tanks South of Sludge Steamroller)"
barbedhook_flotsamvale_mailbox = "Barbed Hook (Flotsam Vale - Butane Tanks Southwest of Mailbox)"
barbedhook_flotsamvale_APunder1 = "Barbed Hook (Flotsam Vale - Air Pocket Cave Underwater 1)"
barbedhook_flotsamvale_APunder2 = "Barbed Hook (Flotsam Vale - Air Pocket Cave Underwater 2)"
barbedhook_flotsamvale_APabove = "Barbed Hook (Flotsam Vale - Air Pocket Cave Above Water)"
barbedhook_flotsamvale_shippingsnail = "Barbed Hook (Flotsam Vale - Behind Shipping Port Snail Shell)"
barbedhook_flotsamvale_shippingbutane = "Barbed Hook (Flotsam Vale - Butane Tank at Shipping Port)"
barbedhook_flotsamvale_trashpile = "Barbed Hook (Flotsam Vale - Trash Pile Past Shipping Dock)"
barbedhook_flotsamvale_consortiumcage = "Barbed Hook (Flotsam Vale - Top of Cage Next to Consortium)"
barbedhook_flotsamvale_consortium = "Barbed Hook (Flotsam Vale - In Front of Consortium)"
barbedhook_flotsamvale_snailfish = "Barbed Hook (Flotsam Vale - Upper Flotsam Vale Fishing Near Snail Shell)"
barbedhook_flotsamvale_westfish = "Barbed Hook (Flotsam Vale - Dunk Lake Fishing West of Sludge Steamroller)"
barbedhook_flotsamvale_behindcubby = "Barbed Hook (Flotsam Vale - Behind Cubby)"
barbedhook_flotsamvale_gunkfish = "Barbed Hook (Flotsam Vale - Gunk Fishing Near Dock)"
barbedhook_flotsamvale_sludgefish = "Barbed Hook (Flotsam Vale - Gunk Fishing Near Sludge Steamroller)"


barbedhook_scuttleport_cubby = "Barbed Hook (Scuttleport - Cubby in First Room)"
barbedhook_scuttleport_magnet = "Barbed Hook (Scuttleport - Platform Next to First Magnet)"
barbedhook_scuttleport_sorting = "Barbed Hook (Scuttleport - In Front of Sorting Chamber Snail Shell)"
barbedhook_scuttleport_magnetdropoff1 = "Barbed Hook (Scuttleport - Platform Under Second Magnet Dropoff 1)"
barbedhook_scuttleport_trashisland = "Barbed Hook (Scuttleport - Trash Island Under Second Magnet Dropoff)"
barbedhook_scuttleport_magnetdropoff2 = "Barbed Hook (Scuttleport - Platform Under Second Magnet Dropoff 2)"
barbedhook_scuttleport_trashblock = "Barbed Hook (Scuttleport - Top of Trash Block on Survivor's Camp Rooftop)"
barbedhook_scuttleport_magrail1 = "Barbed Hook (Scuttleport - Mag-Rail Platform Building 1)"
barbedhook_scuttleport_magrail2 = "Barbed Hook (Scuttleport - Mag-Rail Platform Building 2)"
barbedhook_scuttleport_magrailroof = "Barbed Hook (Scuttleport - Mag-Rail Platform Building Rooftop)"
barbedhook_scuttleport_magrail3 = "Barbed Hook (Scuttleport - Mag-Rail Platform Building 3)"
barbedhook_scuttleport_propanebridge = "Barbed Hook (Scuttleport - Inside Propane Tank Bridge)"
barbedhook_scuttleport_afterbridge = "Barbed Hook (Scuttleport - Past Propane Tank Bridge)"
barbedhook_scuttleport_propaneroof1 = "Barbed Hook (Scuttleport - Rooftop Past Propane Tank Bridge 1)"
barbedhook_scuttleport_propaneroof2 = "Barbed Hook (Scuttleport - Rooftop Past Propane Tank Bridge 2)"

barbedhook_pinbarge1 = "Barbed Hook (Pinbarge 1)"
barbedhook_pinbarge2 = "Barbed Hook (Pinbarge 2)"

barbedhook_unfathom_mimic = "Barbed Hook (The Unfathom - Left of First Mimic)"
barbedhook_unfathom_mimichill = "Barbed Hook (The Unfathom - On a Hill After First Mimic)"

barbedhook_oldocean_northwesthouse = "Barbed Hook (The Old Ocean - Styrofoam House Northwest of Snail Shell)"
barbedhook_oldocean_southhouse = "Barbed Hook (The Old Ocean - Styrofoam House South of Second Island)"
barbedhook_oldocean_secondisland = "Barbed Hook (The Old Ocean - Middle of Second Island)"
barbedhook_oldocean_brokenbridge1 = "Barbed Hook (The Old Ocean - On Broken Bridge to City 1)"
barbedhook_oldocean_brokenbridge2 = "Barbed Hook (The Old Ocean - On Broken Bridge to City 2)"
barbedhook_oldocean_entrance = "Barbed Hook (The Old Ocean - East of City Entrance)"
barbedhook_oldocean_citygates = "Barbed Hook (The Old Ocean - Platform Past City Gates Snail Shell)"
sharkegg_oldocean_citygates = "Shark Egg (The Old Ocean - Southeast of City Gates Snail Shell)"
barbedhook_oldocean_chitan = "Barbed Hook (The Old Ocean - Southeast of Snail Shell Nearby Chitan)"
barbedhook_oldocean_eastsnail = "Barbed Hook (The Old Ocean - East of Snail Shell)"
barbedhook_oldocean_easternbuilding = "Barbed Hook (The Old Ocean - Outside Eastern Building)"
barbedhook_oldocean_middlebuilding = "Barbed Hook (The Old Ocean - Outside Middle Building)"

# stowaway item locations
siphonophore_shallows_westwall = "Siphonophore (Central Shallows - Along West Wall)" # siphonophore stowaway found in the shallow
seastar_shallows_eastledge = "Seastar (Central Shallows - East Ledge Behind Comb Crab)"
whelk_shallows_dune = "Whelk (Central Shallows - Sand Dune Near Flip-Flop Bridge)"
sponge_shallows_puffer = "Sponge (Central Shallows - East Ledge Near Pufferfish)"
anothercrab_shallows_pillar = "Another Crab (Central Shallows - Tall Pillar Near Royal Shellsplitter)"
sanddollar_shallows_arch = "Sand Dollar (Central Shallows - South Arch Wall)"
mussel_shallows_southwestcastlefish = "Mussel (Central Shallows - Dig Spot Near Southwest Sandcastle)"
anemone_shallows_southwestcastlehiddenfishing = "Anemone (Central Shallows - Hidden Fishing on South-Eastern Wall of Castle on South-Western Plateau)"
razorblade_shallows_slacktidebottlefishing = "Razor Blade (Central Shallows - Fishing South West of Slacktide Near Bottles)"
anemone_shallows_umbrellafishing = "Anemone [Stowaway] (Central Shallow - Fishing West of Umbrella)"

limpet_slacktide_stairs = "Limpet (Slacktide - Stairs Left of Main Hallway)" # limpet up the stairs to the left of the main hallway to the duchess in slacktide
seastar_slacktide_grappleroom = "Seastar (Slacktide - Top of Fishing Line Room)" # seastar found by grappling up in the room where the fishing line is found
barnacle_slacktide_bigurchin = "Barnacle (Slacktide - After Big Urchin Spiral Staircase)" # barnacle found after running up the staircase where the giant urchin rolls down toward the player

limpet_snailcave_jelly = "Limpet (Moon Snail's Cave - Ride the First Moon Jelly)"

mussel_slacktide_fortentrance =  "Mussel (Slacktide - Southwest Fort Entrance)" # mussel at the entrance of slacktide after it is corrupted
anemone_slacktide_fortwall = "Anemone (Slacktide - South Fort Wall)" # anemone found on top of the fort wall toward the south
whelk_slacktide_turrettop = "Whelk (Slacktide - Center Castle Turret Top)" # whelk found after climbing up the castle turret in the center of slacktide
rustynail_slacktide_bigurchin = "Rusty Nail (Slacktide - Big Urchin Staircase Grapple Point)"

seastar_reefsedge_crabs = "Seastar (Reef's Edge - Surrounded by Crabs)"
seastarplus_reefsedge_pole = "Sea Star+ (Reef's Edge - Top of Large Hammer Crab Pole)"
whelkplus_reefsedge_sponge = "Whelk+ (Reef's Edge - Near Orange Coral and Sponge)"

limpet_newcarcinia_entrance = "Breadclaw (New Carcinia - Top of Cardboard Buildings Near Entrance)"
rustynail_newcarcinia_hammerhead = "(New Carcinia - On Top of Hammerhead Toolbox)"

sanddollar_newcarcinia_hammerhead = "Sand Dollar (New Carcinia - Flat Coral Near/Above Hammerhead)"

phytoplankton_sandsbetween_centralvista = "Phytoplankton (The Sands Between - Central Vista Center Tunnel)"
anemone_sandsbetween_centralvista = "Anemone (The Sands Between - Central Vista Top)"
anemone_sandsbetween_playground = "Anemone (The Sands Between - Sinkhole filled with Crabs near Playground Town)"
rustynail_sandsbetween_fence = "Rusty Nail (The Sands Between - Near Fence and Rock West of Playground Town)"
googlyeye_sandsbetween_pizza = "Googly Eye (The Sands Between - Microplastics near Southern Pizza Box)"
siphonophore_sandsbetween_cooler = "Siphonophore (The Sands Between - Rocks Southwest of Cooler aka Old Pag Quick Kill Spot)"
limpet_sandsbetween_anchor = "Limpet (The Sands Between - Near Two Bobbit Worms on East Side near Anchor)"
anemone_sandsbetween_chains = "Anemone (The Sands Between - Sinkhole by West Chains)"
fredrick_sandsbetween_fredrick = "Fredrick (The Sands Between - Fredrick's Grave by West Chains)"
anothercrab_sandsbetween_chains = "Another Crab (The Sands Between - Under Chain on West Side)"
mussel_sandsbetween_anchor = "Mussel (The Sands Between - Rocks Below Anchor on West Side)"
barnacle_sandsbetween_northeast = "Barnacle (The Sands Between - Rocks Northeast of Central Vista)"
salp_sandsbetween_northeast = "Salp (The Sands Between - Sinkhole near Rocks Northeast of Central Vista)"
rustynailplus_sandsbetween_centralvista = "Rusty Nail+ (The Sands Between - Mantis Block near Central Vista)"
seastarplus_sandsbetween_flotsam = "Sea Star+ (The Sands Between - Mantis Block near Flotsam Vale Entrance)"
seaslug_sandsbetween_crabrave = "Sea Slug (The Sands Between - Mantis Block below Crab Rave)"
whelk_sandsbetween_crabrave = "Sea Slug (The Sands Between - Mantis Block below Crab Rave)"
sinkerplus_sandsbetween_northridgemantis = "Sinker+ (The Sands Between - Mantis Block North of Secluded Ridge)"
limpetplus_sandsbetween_grovemantis = "Limpet+ (The Sands Between - Mantis Block at Grove Entrance)"
lumpsuckerplus_sandsbetween_anchor = "Lumpsucker+ (The Sands Between - On the anchor, after the electric crab)"
sinkerplus_sandsbetween_southeel = "Sinker+ (The Sands Between - South Eelectrocute Path)"
musselplus_sandsbetween_southeel = "Mussel+ (The Sands Between - South Eelectrocute Path First Jump)"
oyster_sandsbetween_southeelashtray = "Oyster (The Sands Between - South Eelectrocute Path Large Island Ashtray)"
mussel_sandsbetween_bobbitfish = "Mussel (The Sands Between - Fishing Near Bobbit Hill)"
barnacle_sandsbetween_bobbitfish = "Barnacle (The Sands Between - Fishing On Bobbit Hill 2nd Layer)"
whelkplusplus_sandsbetween_southeelpeak = "Whelk++ (The Sands Between - South Eelectrocute Path First Island Peak)"
salpplus_sandsbetween_groveeel = "Salp+ (The Sands Between - Eelectrocute Path Near Grove Small Island)"
usedbandage_sandsbetween_groveeel = "Used Bandage (The Sands Between - Eelectrocute Path Near Grove)"

limpet_ridge_ncliffkelp = "Limpet (Secluded Ridge - North Cliff Hidden in Kelp)"
sanddollar_ridge_broom = "Sanddollar (Secluded Ridge - Near Broom)"
musselplus_ridge_togo = "Mussel+ (Secluded Ridge - Western Cliff To Go Box)"
siphonophoreplus_ridge_pitfall = "Siphonophore+ (Secluded Ridge - Pitfall)"
anemoneplus_ridge_eel = "Anemone+ (Secluded Ridge - Eelectrocute)"
cockle_ridge_eelfish = "Cockle (Secluded Ridge - Fishing on Eelectrocute Path)"
bobber_ridge_broomspire = "Bobber (Secluded Ridge - Broom Spire Climb)"

cockle_trashbin_peak = "Cockle (Trashbin Plateau - Peak)"
sinker_trashbin_peak = "Sinker (Trashbin Plateau - Peak)"
smallbattery_trashbin_mantis = "Small Battery (Trashbin Plateau - Mantis Block)"
googlyeye_trashbin_pineapple = "Googly Eye (Trashbin Plateau - Pineapple)"

barnacle_grovemain_colander = "Barnacle (Expired Grove Main - On Top of Colander)"
seastar_grovemain_eastrock = "Seastar (Expired Grove Main - East Circular Rock)"
pufferquill_grovemain_sponges = "Puffer Quill (Expired Grove Main - Cross Sponge Islands)"
limpet_grovemain_sodacan = "Limpet (Expired Grove Main - Soda Can Stepping Stones)"
lumpsucker_grovemain_canopy = "Lumpsucker (Expired Grove Main - Carton Canopy)"
sharktooth_grovemain_pizza = "Shark Tooth (Expired Grove Main - Under Pizza Box)"
contactlens_grovemain_carts = "Contact Lens (Expired Grove Main - Behind Shopping Cart Buildings)"
cottonball_grovemain_mantis = "Cotton Ball (Expired Grove Main - Mantis Block on Oil Drum Path)"
mussel_grovemain_fishing = "Mussel (Expired Grove Main - Fishing by Entrance)"
sponge_grovemain_fishing = "Sponge (Expired Grove Main - Fishing by Crystal Parkour)"
oyster_grovemain_fishing = "Oyster (Expired Grove Main - River Fishing Under Bridge)"
limpet_grovemain_fishing = "Limpet (Expired Grove Main - River Fishing Before Lichenthrope)"

anemone_grovevillage_fishing = "Anemone (Expired Grove Village - River Fishing Near Cart Mantis Block)"
phytoplanktonplus_grovevillage_upsidedown = "Phytoplankton+ (Expired Grove Village - Top of Upside Down village)"
wadofgum_grovevillage_gumpile = "Wad of Gum (Expired Grove Village - Gum Pile in Hammer Crab Cave)"
anemone_grovevillage_seahorse = "Anemone (Expired Grove Village - Near Seahorse)"
mussel_grovevillage_dock = "Mussel (Expired Grove Village - Dock Fishing Spot 2)"
earthworm_grovevillage_dock = "Earthworm (Expired Grove Village - Dock Fishing Spot 5)"

anemone_flotsamvale_butaneisland = "Anemone (Flotsam Vale - Butane Tank Island East of Main Entrance)"
rustynail_flotsamvale_brokenbutane = "Rusty Nail (Flotsam Vale - In Gunk Under Broken Butane Tank)"
sinker_flotsamvale_woodplatform = "Sinker (Flotsam Vale - Wooden Platform Above Sludge Steamroller)"
mussel_flotsamvale_woodplatform = "Mussel (Flotsam Vale - Wooden Platform Above Sludge Steamroller)"
rustynail_flotsamvale_steamroller = "Rusty Nail (Flotsam Vale - In Gunk Near Sludge Steamroller)"
limpet_flotsamvale_trashpile = "Limpet (Flotsam Vale - Trash Pile Near Sludge Steamroller)"
fruitsticker_flotsamvale_westbutane = "Fruit Sticker (Flotsam Vale - Butane Tanks West of Sludge Steamroller)"
seacucumber_flotsamvale_westbutane = "Sea Cucumber (Flotsam Vale - Butane Tanks West of Sludge Steamroller)"
lumpsucker_flotsamvale_shorcut = "Lumpsucker (Flotsam Vale - Ledge Below Shortcut to Map Piece)"
oyster_flotsamvale_butanemailbox = "Oyster (Flotsam Vale - Butane Tanks Southwest of Mailbox)"
seastar_flotsamvale_butanemailbox = "Seastar (Flotsam Vale - Butane Tanks Southwest of Mailbox)"
anemone_flotsamvale_APunder = "Anemone (Flotsam Vale - Air Pocket Cave Underwater)"
cockle_flotsamvale_APabove = "Cockle (Flotsam Vale - Air Pocket Cave Above Water)"
sanddollar_flotsamvale_APabove = "Sand Dollar (Flotsam Vale - Air Pocket Cave Above Water)"
anemoneplus_flotsamvale_APunder = "Anemone+ (Flotsam Vale - Air Pocket Cave Underwater)"
anothercrab_flotsamvale_mailbox = "Another Crab (Flotsam Vale - Clam Leading Up to Mailbox)"
sponge_flotsamvale_cranegrapple = "Sponge (Flotsam Vale - Crane Grapple Up Toward Expired Grove)"
seastarplus_flotsamvale_submerged = "Seastar+ (Flotsam Vale - Submerged Butane Tank Southwest of Sludge Steamroller)"
lamprey_flotsamvale_islandfish = "Lamprey (Flotsam Vale - Small Island Fishing East of Entrance)"
mussel_flotsamvale_elevatedfish = "Mussel (Flotsam Vale - Elevated Island Fishing)"
siphonophoreplus_flotsamvale_waterfall = "Siphonophore+ (Flotsam Vale - Fishing Near Waterfall)"
whelk_flotsamvale_westfish = "Whelk (Flotsam Vale - West Gunk Lake Fishing)"
anemoneplus_flotsamvale_northwestfish = "Anemone+ (Flotsam Vale - Gunk Lake Fishing Northwest of Sludge Steamroller)"
turtleshell_flotsamvale_gunkfish = "Turtle Shell Shard (Flotsam Vale - Gunk Fishing by Priest)"
lilisopod_flotsamvale_gunkfish = "Lil' Isopod (Flotsam Vale - Gunk Fishing on Docks)"
rustynail_flotsamvale_gunkfish = "Rusty Nail (Flotsam Vale - Gunk Fishing Near Blue Tower)"
barnacle_flotsamvale_gunkfish = "Barnacle (Flotsam Vale - Gunk Fishing Near Middle Tower)"

googlyeye_scuttleport_cubbies = "Googly Eye (Scuttleport - Top of Cubbies in First Room)"
seastar_scuttleport_cubbies = "Seastar (Scuttleport - Top of Cubbies in First Room)"
sanddollar_scuttleport_magnet = "Sand Dollar (Scuttleport - Path to First Magnet)"
mussel_scuttleport_magnetfish = "Mussel (Scuttleport - Fishing Next to First Magnet)"
limpet_scuttleport_electricboxes = "Limpet (Scuttleport - Platform Next to Electrical Boxes)"
rubberband_scuttleport_magnetdropoff = "Rubber Band (Scuttleport - Ledge Before Second Magnet Dropoff)"
limpet_scuttleport_magnet = "Limpet (Scuttleport - Path to Left After First Magnet)"
anemoneplus_scuttleport_magnetdropoff = "Anemone+ (Scuttleport - Platform Under Second Magnet Dropoff)"
lumpsucker_scuttleport_trashisland = "Lumpsucker (Scuttleport - Trash Island Under Second Magnet Dropoff)"
sinkerplusplus_scuttleport_clam = "Sinker++ (Scuttleport - Clam Next to Stationary Magnet)"
seastar_scuttleport_survivorcamp = "Seastar (Scuttleport - Inside Survivor's Camp Building)"
pufferquill_scuttleport_survivorcamp = "Puffer Quill (Scuttleport - Inside Survivor's Camp Building)"
turtleshell_scuttleport_survivorcamp = "Turtle Shell Shard (Scuttleport - Side Platform After Survivor's Camp Magnet)"
rustynailplus_scuttleport_magrail = "Rusty Nail+ (Scuttleport - Mag-Rail Platform Building Rooftop)"
barnacleplus_scuttleport_propanebridge = "Barnacle+ (Scuttleport - Rooftop Past Propane Tank Bridge)"
salp_scuttleport_propanebridge = "Salp (Scuttleport - Rooftop Past Propane Tank Bridge)"
musselplus_scuttleport_voltai = "Mussel+ (Scuttleport - Outside Voltai Arena)"

barnacle_pinbarge = "Barnacle (Pinbarge)"
musselplus_pinbarge = "Mussel+ (Pinbarge)"

musselplus_unfathom_telephone = "Mussel+ (The Unfathom - Next to Telephone by First Mimic)"
seastarplus_unfathom_glowstick = "Seastar+ (The Unfathom - Past Blue Glowstick)"
lanternfish_unfathom_styrofoam = "Lanternfish (The Unfathom - Styrofoam Box Near Pinbarge Shipwreck)"
lampreyplus_unfathom_pinbargeclam = "Lamprey+ (The Unfathom - Clam Northeast of Pinbarge)"
limpet_unfathom_pinbarge = "Limpet (The Unfathom - Ledge Far Northeast of Pinbarge)"
siphonophoreplus_unfathom_shortcut = "Siphonophore+ (The Unfathom - Ledge North of Second Shortcut)"
salp_unfathom_glowstickfish = "Salp (The Unfathom - Fishing Near Red Glowstick)"
barnacleplus_unfathom_pinbargefish = "Barnacle+ (The Unfathom - Fishing Near Pinbarge Shipwreck)"

sinkerplus_plains_petroch = "Sinker+ (Abyssal Plains - Path East of Petroch)"
pufferquill_plains_inkerton = "Puffer Quill (Abyssal Plains - Southwest of Inkerton Arena)"
rustynailplus_plains_shortcut = "Rusty Nail+ (Abyssal Plains - Next to Shortcut)"
limpetplus_plains_inkerton = "Limpet+ (Abyssal Plains - Southwest of Inkerton Arena)"
whelkplus_plains_shortcut = "Whelk (Abyssal Plains - Southeast of Shortcut)"
zooplanktonplus_plains_shortcut = "Zooplankton+ (Abyssal Plains - East of Shortcut)"
salpplus_plains_entrance = "Salp+ (Abyssal Plains - Above Entrance)"
anothercrab_plains_shortcutclam = "Another Crab (Abyssal Plains - Clam On Ledge East of Shortcut)"
seacucumber_plains_entrance = "Sea Cucumber (Abyssal Plains - North of Entrance)"
fruitsticker_plains_entrance = "Fruit Sticker (Abyssal Plains - North of Entrance)"

sanddollar_oldocean_ledge = "Sand Dollar (The Old Ocean - Ledge North of Second Island)"
barnacleplusplus_oldocean_styrofoam = "Barnacle++ (The Old Ocean - Across Styrofoam Block Hooks)"
seastarplusplus_oldocean_entranceclam = "Seastar++ (The Old Ocean - Clam On Building North of City Entrance)"
spongeplus_oldocean_entrance = "Sponge+ (The Old Ocean - North of City Entrance)"
sanddollar_oldocean_citywall = "Sand Dollar (The Old Ocean - Inside City Walls)"
usedbandageplus_oldocean_citywall = "Used Bandage+ (The Old Ocean - Drop Off Onto City Wall)"
cockleplus_oldocean_snaileast = "Cockle+ (The Old Ocean - In Building East of Snail Shell)"
anothercrab_oldocean_elevator = "Another Crab (The Old Ocean - Under Large Elevator)"
sanddollar_oldocean_easternbuilding = "Sand Dollar (The Old Ocean - Inside Eastern Building)"
phytoplanktonplus_oldocean_clam = "Phytoplankton+ (The Old Ocean - Clam Inside Eastern Building)"
musselplusplus_oldocean_woodplank = "Mussel++ (The Old Ocean - Clam in Secret Area Under Wooden Planks)"
whelkplusplus_oldocean_mantis = "Whelk++ (The Old Ocean - Behind Mantis Punch Wall)"

# costume locations
captain_costume_pickup = "Captain Costume (Central Shallows - Near Nephro Spawn)"
clown_costume_pickup = "Clown Costume (The Sands Between - Path of the Clown)"
sunlight_costume_pickup = "Sunlight Costume (Secluded Ridge - Southern Bonfire)"
intern_costume_pickup = "Intern Costume (Expired Grove Village - Intern Costume)"
cowfishboy_costume_pickup = "CowFishBoy Costume (Flotsam Vale - Butane Tank Island East of Main Entrance)"
bluecollar_costume_pickup = "Blue-Collar Costume (Scuttleport - Cubby in First Room)"
krillionaire_costume_pickup = "Krillionaire Costume (The Unfathom - Next to Nemma)"
exiledflame_costume_pickup = "Exiled Flame Costume (The Unfathom - Path North of Blue Glowstick)"
drkril_costume_pickup = "Dr. Kril Costume (The Old Ocean - Between Pill Bottles)"


# adaptation locations
royal_wave_reward = "Royal Wave Adaptation (Fort Slacktide - Defeat Magista)"
urchin_toss_quest = "Urchin Toss Adaptation (New Carcinia - Hug Erich Too Much)"
bobbit_trap_pickup = "Bobbit Trap (The Sands Between - Top of the Bobbit Den)"

# boss locations
royal_shellsplitter = "Royal Shellsplitter" # first hidden/optional boss of the game in the shallows
nephro = "Nephro, Captain of the Guard" # first boss of the game
platoon_pathfinder = "Polluted Platoon Pathfinder" # miniboss that drops the pristine pearl for the duchess
magista = "Magista, Tyrant of Slacktide" # boss of slacktide, also known as the duchess
pagurus = "Pagurus, The Ravenous" #The big bad of the sands between
lichenthrope = "Diseased Lichenthrope" # the first miniboss of the grove
carbonara_connoisseur = "Curdled Carbonara Connoisseur" # behind the gunk waterfall
heikea = "Heikea, Intimidation Crab" # drops a map piece
topoda = "Grovekeeper Topoda"
consortium = "The Consortium"
sludge_steamroller = "Scuttling Sludge Steamroller"
ceviche_sisters = "Ceviche Sisters"
voltai = "Voltai, The Accumulator"
roland = "Roland, Venture Crabitalist"
petroch = "Petroch, The False Moon"
inkerton = "Inkerton, Crab Hunter"
camtscha = "Camtscha, The Bleached King"
praya_dubia = "Praya Dubia, The Ocean's Agony"
firth = "Firth, The Crab Who Stole The Whorl"

# skill locations
shelleport_skill = "Shelleport Skill (Moon Snail)"
skedaddle_skill = "Skedaddle Skill (Moon Snail)"
parry_skill = "Parry Skill (Moon Snail)"
riposte_skill = "Riposte Skill (Moon Snail)"
natural_defenses_skill = "Natural Defenses (Moon Snail)"
aggravation_skill = "Aggravation Skill (Moon Snail)"
self_repair_skill = "Self-Repair Skill (Moon Snail)"
kintsugi_skill = "Kintsugi Skill (Moon Snail)"
skewer_skill = "Skewer Skill (Moon Snail)"
plunge_skill = "Plunge Skill (Moon Snail)"
scrap_hammer_skill = "Scrap Hammer Skill (Moon Snail)"
dispatch_skill = "Dispatch Skill (Moon Snail)"
spearfishing_skill = "Spearfishing Skill (Moon Snail)"
wave_breaker_skill = "Wave Breaker Skill (Moon Snail)"
streamline_skill = "Streamline Skill (Moon Snail)"
housewarming_skill = "Housewarming Skill (Moon Snail)"
circle_of_life_skill = "Circle of Life Skill (Moon Snail)"
elusive_prey_skill = "Elusive Prey Skill (Moon Snail)"
ebb_and_flow_skill = "Ebb and Flow Skill (Moon Snail)"
umami_training1_skill = "Umami Training 1 Skill (Moon Snail)"
umami_training2_skill = "Umami Training 2 Skill (Moon Snail)"
umami_training3_skill = "Umami Training 3 Skill (Moon Snail)"